### ISSUE TITLE
Need to monitor airplane mode

### ISSUE THREAD

**Issue by ehem** [zamojski/TowerCollector#10]
The behavior of TowerCollector is interesting if airplane mode (cellphone off) is turned on while TowerCollector is collecting data.  One may do this due to wanting not to be disturbed.  Once airplane mode is turned on (cellphone on) TowerCollector seemed confused.

**Comment by zamojski** [comment]
It may be more convenient to use 'don't disturb' mode on newer Android versions. Anyway I will investigate this case, thanks for reporting.
