### ISSUE TITLE
Cell ID / RNC missing on map

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#100]
Here we see there is a empty blank line at the bottom of the balloon. The empty line certainly was intended to house Cell ID /  RNC but it is missing.
![Screenshot_20210104-163032_2](https://user-images.githubusercontent.com/1230959/103517907-d8e30f00-4ead-11eb-84f1-ac58f6c2745c.jpg)

**Comment by zamojski** [comment]
You're right there's an empty line, I will fix that. Initially I didn't consider Cell ID / RNC to be presented here but it sounds reasonable. I need to make some tests to make sure it will fit nicely inside the tooltip.

**Comment by jidanni** [comment]
In fact maybe all users like only one of the two styles, so perhaps space could be saved by only showing the one they prefer.
On the other hand, the LAST SAVED panel shows both styles. So perhaps both should be shown here too.
