### ISSUE TITLE
Black upside down teardrop icon on map

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#101]
Here there is a mysterious black upside down teardrop icon with a hole in it. However touching it doesn't reveal what it is supposed to mean.
![Screenshot_20210104-163032_2](https://user-images.githubusercontent.com/1230959/103517907-d8e30f00-4ead-11eb-84f1-ac58f6c2745c.jpg)

**Comment by zamojski** [comment]
The pin icon presents your current location when stationary, when you move it changes to arrow. However it looks a bit strange on your screenshot because I would expect that pin will be centered within the accuracy circle.

**Comment by jidanni** [comment]
OK. So touching it should pop up "Your current location when stationary".

**Comment by jidanni** [comment]
(Here it has moved entirely outside the circle:)
![Screenshot_20210110-171843_1](https://user-images.githubusercontent.com/1230959/104119407-01fe1680-536a-11eb-813a-e648badde934.jpg)
