### ISSUE TITLE
Swiping West on the map goes to the statistics screen

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#103]
Moving the map North and South with your fingers is a breeze. However moving the map to see more easterly is kind of hard. The worst thing is moving the map to see more Westerly. In this case we end up sliding into the statistics page if we are not careful. However being careful means swiping very very slow.

The Problem is when swiping back and forth from Last Saved to statistics it's okay to swipe the whole screen. However from Map to Statistics we should only be allowed to use the top bar to switch between these two windows. And the map should be an independent screen control and the left and right swiping actions should not affect it.

**Comment by jidanni** [comment]
Workaround: first swipe a tiny bit north or south, then without lifting your finger continue east or west.

**Comment by jidanni** [comment]
Actually users want a full(er) screen map window,
not a "claustrophobic" artificially shortened map window due to needing
a switcher panel at top.

Therefore moving the map to its own window, accessible via the main
menu, etc. would "kill two birds with one stone"!

**Comment by zamojski** [comment]
There's no way to improve panning gesture when the map is used in tabbed layout, it's the way Android handles that gesture. However I like the idea to put the map as separate view as an option.
