### ISSUE TITLE
Sometimes we don't want GPS on, when looking at the map

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#104]
There should be a way to turn off GPS when we are looking at the map. Sure, 95% of the time we want the GPS on when we are looking at the map. However, 5% of the time it is not appropriate and we don't want it on. So perhaps on the screen there should be a way to turn off our phone's GPS signal.  Without, of course, leaving the map page or the app.

**Comment by zamojski** [comment]
I will make this option persisted until the app is deleted from system memory. I don't see a reason to keep it between the runs of the application.
