### ISSUE TITLE
Show current map cache statistics in Settings

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#105]
In settings, on the map page, it should show us exactly how many kilobytes are being used currently for the cache.

**Comment by jidanni** [comment]
In https://github.com/zamojski/TowerCollector/issues/115#issuecomment-821775940 we learn it is 150 MB, so I would show that in Settings, even if it is "read-only" (unchangeable).
So
Disk used: 73 / 150 MB.

**Comment by zamojski** [comment]
What's the benefit of showing that value? The current usage may be different that reserved cache space due to performance reason.

According to documentation ` Note that this method currently takes a while.` which will negatively affect performance of the app.

**Comment by zamojski** [comment]
Moreover it's difficult to get that value without showing a map.

**Comment by zamojski** [comment]
Closing as too little profit but too much work.

**Comment by jidanni** [comment]
OK, then just note on the screen "Max cache size: 150 MB".
That way users, even though they can't tell the current size. At least don't have to worry that it will go to 99999999999 MB etc.

**Comment by zamojski** [comment]
You have a dedicated setting for that purpose and it shows current value.
