### ISSUE TITLE
Don't use exact same icon for upload successful

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#111]
In the top of the Android screen there's a little icon that is seen while collecting Towers. This is the exact same icon that is used for the upload successful message. However, users looking at their cell phone will think "my cell phone is still collecting points"... unless of course they have a uncluttered brain and remember their recent actions very clearly. Therefore perhaps use a  big green check mark on top of the icon so they can distinguish different icons. Okay maybe Android does not allow one to do this.  Well that's too bad. Maybe somebody should file a bug  with Android.

**Comment by mizzunet** [comment]
Here are the icons that make use of it I guess
Uploading: https://thenounproject.com/term/uploading/835400/
Finished: https://thenounproject.com/term/tick/317777/
