### ISSUE TITLE
Feature request - only upload newly discovered cells

### ISSUE THREAD

**Issue by botistreamer** [zamojski/TowerCollector#113]
Only upload newly discovered cells.

The reason for this feature is that I can always keep Tower Collector running without fear of taking multiple measurements of the same cells (on different days).

**Comment by zamojski** [comment]
Discovered cells are not the ones which are not duplicated. These are the cells that your phone has seen for the first time. Assuming that one cell tower has few square kilometers of coverage, if you don't travel throughout whole covered area you won't be able to upload the data for the second time (cell will be considered as previously known). What's your point of view?

**Comment by zamojski** [comment]
Any comments or thoughts?

**Comment by botistreamer** [comment]
Yes I agree with your point of view. Sorry I am not active on github.
