### ISSUE TITLE
App using GPS when not necessary

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#114]
App uses GPS, even when not recording and even when not looking at the map page.

**Comment by jidanni** [comment]
It turns out only the "last saved" page is immune from the bug.

**Comment by jidanni** [comment]
Also, and preferences, if one turns off the map, the bug also goes away!

**Comment by zamojski** [comment]
The reason behind this behavior is how Android manages memory of the visible content of the screen. If you swipe away from the map (to the first tab) it considers the opposite edge tab to become inactive and deactivates it. But if you're close to the map tab, like on the statistics tab, Android assumes you may want to get back to the map tab very soon. Taking that assumption it doesn't deactivate the tab and GPS remain active.

I could potentially deactivate GPS while you're not on the map tab but I don't see a reason to do it. How often do you keep the app visible on the screen while not collecting measurements? I see that to happen when you export or upload data (longer activity) or when looking at the map or the other tabs. This doesn't really hurt the battery if you do it for 30 seconds.

**Comment by jidanni** [comment]
So #103 would also fix this bug.

There is no guarantee what state the user will put the phone in his pocket in.

If you see GPS is still on for no reason ... he will be afraid to put his phone in his pocket!

**Comment by zamojski** [comment]
I've checked that whenever you block the screen it will disable GPS which is used on the map tab.

**Comment by jidanni** [comment]
Well the user still worries...

**Comment by zamojski** [comment]
I did a test on couple of phones and the GPS icon disappears when I leave the map tab. However, it appears to be present when you minimize the app on Statistics tab and then restore the app, even though that Map tab is not active. I will fix it.
