### ISSUE TITLE
Don't force turning off the map to clear the cache

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#115]
All I wanted to do was turn off the map temporarily. What does that have to do with clearing the cache? Why can't the two operations be separated somehow. There already is a clear the cache option at the bottom of the menu.

**Comment by jidanni** [comment]
![Screenshot_20210416-120914.jpg](https://user-images.githubusercontent.com/1230959/114970661-6c64ac80-9ead-11eb-8b05-0a2f4a712ccf.jpg)

**Comment by zamojski** [comment]
What would be the reason to temporarily disable the map?

**Comment by jidanni** [comment]
Well, let's say we are just a conservative user, who e.g., doesn't usually drive around with his sunroof open even though he has one on his car.

And also let's say we live in an underdeveloped country so don't have unlimited data. So our map cache is rather important to us!

**Comment by jidanni** [comment]
Also, let's say we are just curious. We just want to see if  turning off the map will make the app run even more wonderfully.

But we are faced with giving up our megabytes (gigabytes? #105) of cache  just to try it for a minute. So we chicken out.

**Comment by zamojski** [comment]
I would rather implement a feature to disable map while connected to mobile data and allow to load it only on WiFi. Regarding the cache size it's currently set to 150 MB, so if you scroll far away it will anyway clear the old view.

**Comment by jidanni** [comment]
Well whatever you do, please don't glue too many features to the same button, as different users may have different needs.
