### ISSUE TITLE
Upload Succesfull but now data in opencallid account / cellmapper

### ISSUE THREAD

**Issue by derpeter** [zamojski/TowerCollector#116]
While collection of data seems to work fine and the track / towers are shown in the map they vanish from the phone after i press the upload button. A popup appears that confirms that the upload was successful. Sadly no data is showing up my opencallid account or cellmapper. (Not sure how to check if data went to mozilla location service).

So far i did not find a way to figure if this is an actually an issue of the app or the API on the server side. Any hints to solve this would be grade. 

Running latest fdroid version (2.7.4) on pixel 5 with android 11

Update:
We tried it on an Fairphone with a different account and same result

**Comment by zamojski** [comment]
Tower Collector doesn't support uploads to cellmapper. Regarding Mozilla Location Services - it uses shared API key and it's not possible to check if the data was uploaded and processed. On the OpenCellID side it may take up to few hours before the data is available publicly.

Can you describe how do you verify that the upload was successful or not? How long did you wait after uploading?

In the OpenCellID panel the 'Usage' tab presents the information about query operations taking place using your API key (Access Token). Again, the statistics may not be updated immediately but with a delay. I remember there was a 'Contribution reports' tab to present the uploads, not fully functional, but currently I don't see it currently in my profile. I think currently the only way to check that is to ask hello@opencellid.org to provide you the contribution report.

**Comment by derpeter** [comment]
Hey @zamojski 

sorry i was not precise here, i meant the upload to https://my.opencellid.org/ . cellmapper seems to use this data (or not doesn"t matter for this issue). 

I checked https://my.opencellid.org/dashboard but maybe this is only for "downloads', there is another page https://my.opencellid.org/dashboard/accesstokens/view which tells my the api token was never used. I uploaded data 4 days ago. 

But since today a point in the map appeared which has the right date. So it seems it has worked. So maybe its only a UI issue on opencellid.

**Comment by zamojski** [comment]
The 'dashboard' is only for downloads, probably the 'access tokens' view is also for that use case.

As I've mentioned there was a 'Contribution reports' tab but I don't see it know. I think the only way to confirm how it works is to ask hello@opencellid.org . I've sent them an email but please do it on your own to check if the data from your phone is present there.

**Comment by derpeter** [comment]
Thanks you for the explanation. Maybe the popup should say something like "Upload successful, it can take some time before the data appears on the website"

**Comment by zamojski** [comment]
I just received a message from OpenCellID saying that the contribution reports feature is not ready yet and it will take them some time to enable it. They also mention that you @derpeter can send them an email with access token and they will generate a report for you.

**Comment by derpeter** [comment]
Thank you again for reaching out to opencellid and make this more clear!
