### ISSUE TITLE
Can I still contribute to MLS... while using MLS?

### ISSUE THREAD

**Issue by lolrepeatlol** [zamojski/TowerCollector#120]
Hey, so I'll make this quick since I know this isn't exactly a typical issue.

I rock a degoogled Pixel w/ microG. By default, my microG configuration came with Mozilla Location Services.

![Screenshot_20210513-171123.png](https://user-images.githubusercontent.com/17863082/118188553-922e9400-b40e-11eb-94d6-29a5a75f9186.png)

So I'm wondering, can I still contribute to MLS if I'm literally *using* MLS? Or would that screw things up? (Apologies, I'm not exactly 100% sure how this works, all I know is that it collects wireless networks around you.)

**Comment by zamojski** [comment]
Hi, I also don't know how this works in detail but I think the system and the app will not interfere each other as they're independent and must use different API keys.

**Comment by lolrepeatlol** [comment]
> 
> 
> Hi, I also don't know how this works in detail but I think the system and the app will not interfere each other as they're independent and must use different API keys.

Thanks for the answer, @zamojski. I understand that, but the thing I'm worried about is that the location I'm sending is wrong.

As I understand, this app sends wireless networks around my area and associates them with my GPS coordinates. Since MLS is sending those GPS coordinates though, wouldn't that effectively make my contributions useless? Or am I misunderstanding how this works? Thanks in advance.

**Comment by zamojski** [comment]
Do you see somewhere there GPS settings? I don't believe that it's not present in the system and the phone only uses network based location.

**Comment by zamojski** [comment]
@lolrepeatlol Any comments or questions from your side?

**Comment by lolrepeatlol** [comment]
> @lolrepeatlol Any comments or questions from your side?

no, i think i'm ok now!! i couldn't find any GPS settings (just location) but considering i have a fairly high-end phone, i don't imagine that the phone *doesn't* have GPS. and from what i've seen on the map, there doesn't really seem to be any anomalies or issues that i've noticed, so i think we can close this issue. thanks for following up!!
