### ISSUE TITLE
QS Toggles for Start, Stop and maybe for Upload as well

### ISSUE THREAD

**Issue by mizzunet** [zamojski/TowerCollector#121]
Could you make this so it's easier to start locating the tower when going out of the home? In this current situation, I rarely get out of the home.
Thanks

**Comment by zamojski** [comment]
What is QS Toggles?

**Comment by mizzunet** [comment]
> What is QS Toggles?

![Screenshot_20210603-222212](https://user-images.githubusercontent.com/10193999/120682518-2ba31000-c4ba-11eb-97b5-d1fc54c19877.png)
Quick Settings button, I meant

**Comment by mizzunet** [comment]
Thanks (;
