### ISSUE TITLE
Movement detection by Significant Motion

### ISSUE THREAD

**Issue by mizzunet** [zamojski/TowerCollector#123]
How is the current method uses for detecting movement? I felt like it queries location data very much while at stationary. And that would drain the battery, wouldn't they? 
While Mozilla Stumbler can use Significant Motion stuff over Accelerometer to detect motion that I think would save battery by not querying location at stationary. What do you think of it?

[Screenshot](https://i.ibb.co/Th5d8bR/Screenshot-20210618-195137.png)

**Comment by zamojski** [comment]
Generally speaking it's a good idea. It has been requested long time ago but it's a high risk and complex change. I'm experimenting with significant motion detection currently so it may be finalized this year.

Duplicate #6
