### ISSUE TITLE
Dont delete my previous messurments on the map

### ISSUE THREAD

**Issue by shukari** [zamojski/TowerCollector#124]
It would be cool if i can toggle on my already mapped messurements.  
ATM it deletes all markers on the map if i upload it. So i dont upload that i can see where i was and where i need to go with 2g, 3g and so on...  
So, can there be an option to first dont delete my mesurements on upload?
And can there be an option on the map (a layer) to show these previous messurements to see where are spots that need to be mapped?

This would made it possible to better collect and to minimze double messurements of the same region.

BTW cool app, thank you for your time and effort 👍

**Comment by zamojski** [comment]
I think this one is related to #17. I put some explanation there but it doesn't mention the map feature. What do you think?

**Comment by shukari** [comment]
Yeah, it is what you mention there.  
The performace problem could be faced if you save it in extra database (like you mentioned) and if you can add layers.  
Im not so familiar with you implementation but if you would have layers on the map it didnt need so much performance or?  
  
Layers:
- [x] Uploaded
    - [ ] 4G
    - [x] 3G
    - [ ] ...
- [x] not uploaded
    - [ ] 4G
    - [x] 3G
    - [ ] ...

That you can (un-)select the hole group of all already uploaded entries and also only the subgroup 3G if you only interested on collecting these atm. So i can collect 3G and see only entries of 3G... saved and not saved ones.

**Comment by shukari** [comment]
I close this one... because the other ticket is much better explained.
