### ISSUE TITLE
Document rescuing uploaded points

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#125]
I recall the upload button it when it was finished asked us if we wanted to keep a copy somewhere. Apparently it doesn't do that anymore,  so now the points I wanted to keep a copy of are uploaded and gone.

So how can the user get a copy of those last few points from the two upstream sites he uploaded it to? I recall that's not very easy anymore either.

No, the user doesn't want to download one million points. Just 100.

**Comment by jidanni** [comment]
So now I'm looking in settings. The Configurator Switch has gotten turned off. Which causes the new default to be uploading things anonymously to be in effect. So my whole upload went through anonymously. Isn't that wonderful? No.

**Comment by jidanni** [comment]
Okay now I have set the settings to make it act like it used to be. But still you should provide some instructions for how people can rescue recent data from Upstream. Even though they "accidentally" uploaded anonymously. But still there should be a way to use a bounding box to get their data back. Yes you are not responsible for how the Upstream servers work, but still you should give people some tips that are tested and put them in the documents somewhere. Thanks.

**Comment by zamojski** [comment]
> I recall the upload button it when it was finished asked us if we wanted to keep a copy somewhere.

There wasn't any feature like this.

> The Configurator Switch has gotten turned off.

The default value you can find in the code. The default setting is to show it. You had to switch it off.
https://github.com/zamojski/TowerCollector/blob/9a8ede1a5eb9d4047476456e7ed649b4ca4f000c/app/src/main/res/values/constants.xml#L31

If you use your own Access Token you'll be able to retrieve uploaded measurements but with anonymous upload - it's supposed to be anonymous without option to recover it. Once #17 is implemented you will be able to keep the measurements locally.

**Comment by jidanni** [comment]
OK some cosmic ray has knocked around my Preferences.

#17 may be great, but many users can live without it, until one day it is too late and they wished they saved something, and want it back... So it would be great if someone tested if it was possible to retrieve something from upstream... Or as you said at the beginning of #17, that that wasn't working...
