### ISSUE TITLE
Switch from Mozilla Public License to GPL

### ISSUE THREAD

**Issue by DistantParadox** [zamojski/TowerCollector#13]
Why you should switch: 

The Mozilla Public License (MPL) was originally created by Mozilla, but its GPL-incompatibility caused so many problems that Mozilla eventually re-licensed their work under a GPL/LGPL/MPL triple license.  It's important to note that even the original creator of the MPL 1.0 and 1.1 abandoned it as their sole license, because of GPL-incompatibility; don’t duplicate their mistake. Google no longer lists the MPL as a recommended license, even though they once did.

The following clause means that this license will (and may already) have conflicts with other open source licenses:

```
1.5. "Incompatible With Secondary Licenses"
    means

    (a) that the initial Contributor has attached the notice described
        in Exhibit B to the Covered Software; or

    (b) that the Covered Software was made available under the terms of
        version 1.1 or earlier of the License, but not also under the
        terms of a Secondary License.
```

Hence, we should switch to the GNU GPL as it is the most widely used free software license and has a strong copyleft requirement whereas the Mozilla Public License 2.0 is seen as a "[weak copyleft](http://choosealicense.com/licenses/mpl-2.0/)".  Additionally, as previously stated, it will prevent further issues of incompatibility for anyone who wants to fork this project.

All that needs to be done is change the license to the GPL in this repo and it will affect all further versions.  Simple as that.

**Comment by zamojski** [comment]
Please read last few paragraphs of the license. Exhibit B is not present in source code files so my MPL is compatible with secondary licenses.

```
If You choose to distribute Source Code Form that is Incompatible With
Secondary Licenses under the terms of this version of the License, the
notice described in Exhibit B of this License must be attached.

Exhibit A - Source Code Form License Notice
-------------------------------------------

  This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at http://mozilla.org/MPL/2.0/.

If it is not possible or desirable to put the notice in a particular
file, then You may include the notice in a location (such as a LICENSE
file in a relevant directory) where a recipient would be likely to look
for such a notice.

You may add additional accurate notices of copyright ownership.

Exhibit B - "Incompatible With Secondary Licenses" Notice
---------------------------------------------------------

  This Source Code Form is "Incompatible With Secondary Licenses", as
  defined by the Mozilla Public License, v. 2.0.
```

**Comment by zamojski** [comment]
You can find question about Exhibit B in the [MPL 2.0 FAQ point Q25](https://www.mozilla.org/en-US/MPL/2.0/FAQ/).

```
Q25: What happens if someone doesn't use the per-file boilerplate, 
and just ships a copy of the full MPL 2 with their code?

The code is licensed under the plain MPL 2. It is not considered 
Incompatible with Secondary Licenses. Making code Incompatible 
with Secondary Licenses requires an active choice on the part 
of the licensor; it is not the default. The notice in Exhibit B 
is not considered "attached" merely by being present as the Exhibit B 
of a copy of the full MPL 2.

The only exception is if the code used to be straight MPL 1.1 and 
was upgraded to MPL 2, in which case it would be Incompatible 
with Secondary Licenses (Sec. 1.5 b).
```

Answering your request to switch to GPL: I don't see any reason to do that. You can use MPL licensed source code in GPL licensed app as long as you comply with MPL.
