### ISSUE TITLE
Add share by email, etc.

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#131]
If sometimes one is not able to save an export, please add alternative ways to share an export. For instance email Etc.

**Comment by zamojski** [comment]
I see Gmail on my list of applications. It probably depends on the email client you use. What's its name?

**Comment by jidanni** [comment]
Gmail.
I don't recall TowerCollector has a "share" button.

**Comment by zamojski** [comment]
It does, when the export is finished you have 4 possible options: delete, keep, share, open.

**Comment by zamojski** [comment]
![Screenshot_20210724-085216](https://user-images.githubusercontent.com/12007817/127273024-d745eb00-1f0b-4259-9f5b-f6c9da6833b2.jpg)

**Comment by jidanni** [comment]
Ahhh... but let's say the export fails / never finishes. That's my point of this bug report.

**Comment by zamojski** [comment]
If export fails the partially created files are deleted. What would you like to share in that scenario?

**Comment by jidanni** [comment]
I was thinking: instead of the user pushing "export",
he could instead push "share", whereupon the app would gather whatever data is was going to export,
and instead directly hand it over to gmail.
The user would then see a gmail screen, with a file already attached, and waiting for him to enter an address and a subject and maybe some words "Hey Ralph, here's the data."

**Comment by jidanni** [comment]
Actually, all that needs to be done is to clean up the confusion for #130, so people could find their exports in the first place. So I will close this request.

**Comment by zamojski** [comment]
> push "share", whereupon the app would gather whatever data is was going to export
That's not possible because to open share window you need to already have all data prepared in advance. I think that current approach is the best we can have. I'm working on making it possible to start export from shortcuts and other apps, so you'll be able to automate it. However it will not allow to open share window from background.
