### ISSUE TITLE
Mention size of usage statistics sending

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#132]
Inside the app there is a discussion of usage statistics. Oddly the user can't copy any of the text on that page! Anyway in that discussion please mention the average size of what is being sent. Some  users don't care what you send, they just want to know how many kilobytes it is going to be, and how often.

**Comment by zamojski** [comment]
The size is not fixed because it sends measurements which may have different number of cells.

**Comment by jidanni** [comment]
Okay that's fine, but say if it's in the range of kilobytes, megabytes, xcetera. Give the user some ideas. The only reason why I turned it off is that I'm worried you are sending  a horrendous amount of data. So so please give the user some firm ranges. Thanks.

**Comment by zamojski** [comment]
I'm closing the issue as with my limited time availability for this project I plan to focus on more important features.
