### ISSUE TITLE
User not allowed to rotate the screen

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#133]
Users are not allowed to rotate the screen. This causes some of the longer titles in Preferences to have no way to be read completely. The user wants to change from portrait to landscape but the app does not permit it.

(Yes, the user has fonts set larger in Android settings.)

**Comment by zamojski** [comment]
Related #112

**Comment by jidanni** [comment]
![Screenshot_20210731-101449.jpg](https://user-images.githubusercontent.com/1230959/127822445-7f99769e-75b7-4be3-82cc-e817361a906d.jpg)
Here we see text is cut off. The word contributions is chopped, with no way to recover it. This creates an actual Accessibility Issue!

That makes the whole app not pass "accessibility qualifications."
