### ISSUE TITLE
150 what? Add unit to cache size setting

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#135]
![Screenshot_20210731-134437.jpg](https://user-images.githubusercontent.com/1230959/127820439-a1b7767b-3896-4d28-85bb-e6e7f8ac8a83.jpg)
This makes no sense without mentioning units. Nobody knows if you're talking about kilobytes or megabytes or gigabytes.

**Comment by jidanni** [comment]
Please don't add a newline. One space would be fine.

**Comment by zamojski** [comment]
With the new line the style is consistent for all settings within the app.
