### ISSUE TITLE
Map question mark button should explain other buttons

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#141]
At the bottom of the map there is a button with a "?" on it.

Currently that button only explains the colors of the dots. It should also explain the meanings of the other three buttons.

**Comment by zamojski** [comment]
You can see the button description if you long press it.

**Comment by jidanni** [comment]
> You can see the button description if you long press it.

Maybe the "(?)" should mention that fact, as most users would not guess that.

**Comment by zamojski** [comment]
> most users would not guess that

That's the standard Android behavior, you can check it yourself in any app that correctly implements buttons for people with reduced vision or they ones using screen readers.
