### ISSUE TITLE
Parenthesis unclear 

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#142]
![Screenshot_20210901-070359.jpg](https://user-images.githubusercontent.com/1230959/131586891-58f13617-6d62-4292-8dc6-fa27cda00962.jpg)
![Screenshot_20210901-070350.jpg](https://user-images.githubusercontent.com/1230959/131586907-b1549c43-ce57-484a-8d86-686c11236045.jpg)
The Cells Today message, should say what exactly is not in the parentheses, and what is the exactly within the parentheses. The current wording is unclear and the parenthesis don't exactly seem to represent the parentheses in the first image.

**Comment by jidanni** [comment]
Use a separate sentence for each. Currently the () blur the grammar/matching.

**Comment by jidanni** [comment]
And be sure both sentences don't have any "( )" in them at all!

I would submit a pull request, except I don't exactly understand the meaning myself!

**Comment by zamojski** [comment]
In the parentheses you have the number of cells that were collected for the first time on this device, never recorded before.
