### ISSUE TITLE
Make sure it's clear about which exported data you're talking about

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#150]
Hear the user is worried  that it is going to delete **all** exported data.
So you need to reword it  to make sure it's only talking about **this** exported data.

![Screenshot_20210908-155132.jpg](https://user-images.githubusercontent.com/1230959/132469759-e4ae9905-9818-4bf0-aa32-b515c81b7744.jpg)

**Comment by zamojski** [comment]
In fact it deletes all measurements from the phone but not the statistics and collected cell towers like Clear option.

**Comment by zamojski** [comment]
Maybe `Are you sure you want to permanently delete locally stored measurements?` is a better message?

**Comment by jidanni** [comment]
You probably need a much longer explicit message, saying what you are going to delete and what you are not going to  delete, like you said "but not the statistics and collected cell towers".
