### ISSUE TITLE
Add shortcut to map settings from map page

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#151]
When looking at the map, if one wants to adjust the map settings, one has to climb all over the menu to finally get to the Map Settings. Therefore it would be great to have a little cogwheel, to get directly to Preferences' Map Settings page.

**Comment by zamojski** [comment]
Which settings do you want to adjust?

**Comment by jidanni** [comment]
Just a simple button that is a shortcut to going into the menu and pressing preferences and then selecting map.

**Comment by zamojski** [comment]
How often and which features do you adjust there?

**Comment by jidanni** [comment]
I don't visit it often. I just thought it would be a great place to make a shortcut, saving the user several taps.

**Comment by zamojski** [comment]
I'd like to focus on more important and useful features.
