### ISSUE TITLE
People are looking for the anonymous contributions Mozilla button

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#154]
In the Preferences there are settings for anonymous opencellD contributions. But there are no settings for anonymous Mozilla contributions. Therefore there should be a slider button for anonymous Mozilla contributions. But it should be locked in the ON position. With an explanation that Mozilla _only_ allows anonymous contributions.

**Comment by zamojski** [comment]
Who are the people you mention? It's like this for years and nobody even asked about our so far.

**Comment by jidanni** [comment]
Well it looks like:

1. "We can register our contributions under our own name at Mozilla, but
TowerCollector just takes the easy way, tossing them to Mozilla
anonymously. Causing us to not be able to look them up later on
Mozilla."

When in fact the truth (still?) is:
2. "Mozilla doesn't have a way to send an ID along with contributions."

I'm just saying looking in Preferences, it appears (1) is the true.
So there should be some mention there in Preferences that that is not
the case.

**Comment by zamojski** [comment]
> The "old" leaderboard switched into "new" in 2016, the "new" leaderboard retired around 2018. https://wiki.mozilla.org/CloudServices/Location

The leaderboard is no longer available: https://location-leaderboard.services.mozilla.com

The API Keys are intended to be used by application developer, so the only way is to contribute anonymously. I don't see a reason to highlight this.
