### ISSUE TITLE
Add X button to close post-export menu 

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#156]
Say a user just wants to export.
OK, that works, and now he sees:

![Screenshot_20211214-200651](https://user-images.githubusercontent.com/1230959/146005996-bffb70f0-5ef6-4005-9071-cfbf437c859a.jpg)

He thinks: I don't want to do any of the choices here.

So there should be an X button in the upper right.

Yes, he can just close the whole app.

But if there was an X, that would reassure him that nothing bad will now happen.

Sorry if I submitted this before. I can't find it.

**Comment by zamojski** [comment]
You can use back gesture / button to close the screen. Current implementation is done according to Android guidelines.
