### ISSUE TITLE
Share button + SHARE choice: confusing

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#157]
Thanks for fixing #73, alas currently there is the very confusing "share" twice now: a share button, and then a SHARE choice.
![Screenshot_20211214-200651](https://user-images.githubusercontent.com/1230959/146005996-bffb70f0-5ef6-4005-9071-cfbf437c859a.jpg)
Yes I'm sure it all makes sense, but not to beginners.

**Comment by zamojski** [comment]
The text on the button is aligned with the selected option, in my opinion it clearly explains what's going to happen.
