### ISSUE TITLE
Same route on the same day - new cellular base stations discovered?

### ISSUE THREAD

**Issue by olekstomek** [zamojski/TowerCollector#165]
I drove a distance of about 140 km. I believe 95% or more of it was the same way back. Distance measured on the same day (approximately 9-10 hours difference). I had two SIM cards from different operators. Is it possible that 112 new cellular base stations have been discovered? I can see the value of `254 (112)`.

**Comment by zamojski** [comment]
Can you share the exported days in CSV to me by email? You can find out in the app.

**Comment by olekstomek** [comment]
Thank you for contact and analysis. I am closing this issue. 
The collected data does not confirm the problem on the application side. I am open to the possible repetition of the tests. 
Thanks again!
