### ISSUE TITLE
Allow creating subdirectories at any level

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#169]
Hear the "create a folder" option is only available at the top level. Let's say we pick a subdirectory here and then wish to create a folder in that subdirectory. Well the choice to create a subdirectory should also be available no matter where we have browsed to here.
Also maybe fill in a default name of TowerCollector for the name we are about to create.
![Screenshot_20220802-162458_Files.jpg](https://user-images.githubusercontent.com/1230959/182476606-7ed3ae29-9b10-4d14-93c3-8fb23839d3a9.jpg)
![Screenshot_20220802-162510_Files.jpg](https://user-images.githubusercontent.com/1230959/182476628-d0e6bf21-6bc5-4594-9692-2df0a5858aeb.jpg)

**Comment by jidanni** [comment]
OK, I tried to make one deep from the top level. And the results were my slash got changed to an underline!
![Screenshot_20220802-163242_Files.jpg](https://user-images.githubusercontent.com/1230959/182477378-ac72c793-b415-470e-a74d-5fc8042ab052.jpg)
![Screenshot_20220802-163302_Files.jpg](https://user-images.githubusercontent.com/1230959/182477405-bce4d1df-f653-4b30-aab1-45005decb654.jpg)

**Comment by zamojski** [comment]
This is the default android file picker, I'm not able to alter it's features and behavior from application point of view. Since Android 10 (I think) it's not possible to grant permissions to root folder.

**Comment by jidanni** [comment]
I'm saying the app offers to create a new directory in /sdcard/, so it should also make the same offer in /sdcard/somedir/ .
I'm not talking about in /.

**Comment by zamojski** [comment]
It's officially supported by Android to provide initial path but according to my tests it doesn't work in most of the cases (depending on the phone). The requirement however is that the initial path already exists in the system.

**Comment by jidanni** [comment]
(OK, if the user wants a new subdirectory, he should use his stock file
manager.)
