### ISSUE TITLE
Retrieve access tokens

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#170]
It's user already has a token, but not yet on this cell phone, he needs a way to get it back from the open cell ID site, instead of only being to create a new token.
![Screenshot_20220802-164451_Tower Collector.jpg](https://user-images.githubusercontent.com/1230959/182479085-fe9bc0a2-1d49-4612-b09a-a8620ff6de4a.jpg)

**Comment by jidanni** [comment]
(By the way the user might also want to create a new style token instead of using the old one)
![Screenshot_20220802-164747_Chrome Dev.jpg](https://user-images.githubusercontent.com/1230959/182479404-0d66db99-3f48-4124-884b-992010705b5e.jpg)

**Comment by zamojski** [comment]
You don't need to create a new key, instead you can recover the old one as you did on the second screenshot.

You can use any type of token as long as it's accepted by OpenCellID.
