### ISSUE TITLE
upload to WiGLE

### ISSUE THREAD

**Issue by az0** [zamojski/TowerCollector#179]
The WiGLE project collects Bluetooth, wi-fi, and cell data, so how about Tower Collector also uploads cell data to WiGLE?

The WiGLE app for Android does not have an option to turn off wi-fi collection, so this would be nice for people who want to contribute only cell data to WiGLE.

**Comment by zamojski** [comment]
Since WiGLE seems to be quite closed project I've decided to implement upload to BeaconDB - the successor of MLS.
