### ISSUE TITLE
Document "enable my location" button

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#184]
Here, mention what the "enable my location" button does.![Screenshot_20221010-183431_Tower Collector.jpg](https://user-images.githubusercontent.com/1230959/194962346-e4e36070-80a9-4c1c-aab0-95de1b76718e.jpg)
You might say this page is only for the map legend, but we hit the question mark button. So we might think that perhaps we can learn what the other buttons do. Other than just what their names are, which is all we see when long pressing them.

**Comment by zamojski** [comment]
Closing as not planned.
