### ISSUE TITLE
no collection with NR SA mode

### ISSUE THREAD

**Issue by az0** [zamojski/TowerCollector#188]
When using Tower Collector with Galaxy A13 5G or Galaxy S22 when they are in NR SA mode, the collection stops.

I do not have collection problems on these phones or other phones with LTE, UMTS, CDMA, and GSM. Only NR SA is the problem. On the map, there are no dots. In the first tab, there is nothing for NR related to "last saved."

**Comment by zamojski** [comment]
Can you please try running NetMonster app at the same time and check what it shows for this network?

You can also try changing API version to 4.2 in Advanced preferences in Tower Collector

**Comment by az0** [comment]
![Screenshot_20221216_095929_NetMonster](https://user-images.githubusercontent.com/933680/208150463-06086691-f88a-40b1-8516-5033e0089d6e.jpg)

![Screenshot_20221216_100241_Tower Collector](https://user-images.githubusercontent.com/933680/208150637-7654844a-fe3b-452b-8242-2d69eb4aae1b.jpg)

Ok, I changed the API version, but it's still just recording LTE for the eSIM and ignoring NR SA for physical SIM.

**Comment by az0** [comment]
In Tower Collector 2.14.2, it's the same: no collection for NR SA.

Still using API 4.2, Samsung Galaxy S22, Android 13

**Comment by zamojski** [comment]
Mozilla Location Services is not actively developed anymore so I guess they reject the cells during server side processing. Or maybe just the documentation is outdated...

**Comment by az0** [comment]
NR collection started working in a recent update to the Tower Collector app
