### ISSUE TITLE
Display information if multi SIM supported

### ISSUE THREAD

**Issue by zamojski** [zamojski/TowerCollector#19]
Display information if the feature is supported by the device.

**Comment by ehem** [comment]
Guess I should add the comment, the _real_ value of this is the ability to take multiple measurements at the same time.  Looks like the crucial data is available via the [SubscriptionManager](https://developer.android.com/reference/android/telephony/SubscriptionManager.html) service as the class [SubscriptionInfo](https://developer.android.com/reference/android/telephony/SubscriptionInfo.html).

**Comment by zamojski** [comment]
You're right. There's one more thing that is required to collect multiple cells at the same time - the Android 4.2 API needs to be correctly implemented by manufacturer which can be checked of course.

**Comment by zamojski** [comment]
Unfortunately there's no way to clearly state whether it is supported. It may happen that when you start collecting there's no signal and compatibility detection will use fallback API 1.0 which doesn't support multi-SIM (newer API may not work correctly so cannot be used). In the end you cannot say if the phone doesn't support this feature.

Detection could be more accurate if based on statistics when used on longer term but never correct for 100%.
