### ISSUE TITLE
Signal strength not available

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#190]
![Screenshot_20221215-104042_Tower Collector.jpg](https://user-images.githubusercontent.com/1230959/207966398-484577d3-cca5-4ba2-9f32-fc57167272e9.jpg)
Sorry I can't reproduce this problem again. All I know is I looked and that's what it said. (I then fired up a different app:
![Screenshot_20221215-104155_Netmonitor.jpg](https://user-images.githubusercontent.com/1230959/207966638-63efb278-6293-4c04-b5f6-837a2b1a21aa.jpg)
And that app has no problems getting the signal strength.)

Minutes later a second reading for the same CID did not have that problem.

**Comment by zamojski** [comment]
Cannot reproduce.
