### ISSUE TITLE
Adjusting preferences causes skipping of recording

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#193]
Here I made a note to myself about the result of looking at, changing some innocent settings in Preferences.
![Screenshot_20221206-221624_Tower Collector](https://user-images.githubusercontent.com/1230959/211231019-ff3f1d64-df31-4913-a0a0-2c17becd45c9.jpg)

**Comment by zamojski** [comment]
Which innocent preferences did you touch?

**Comment by jidanni** [comment]
I forgot which ones. And also maybe the gap could be caused by unrelated issues. So I guess I'll just close this.
