### ISSUE TITLE
Question: is the import measurements.db feature overwriting existing values on the importing phone, or is it appending imported values, to existing ones?

### ISSUE THREAD

**Issue by chipechop** [zamojski/TowerCollector#195]
Hi, (question 1) is the import measurements.db feature lossless (is it appending measurements to existing ones), or is it an overwriting feature (is it erasing the existing values, in my measurements.db)?

In the latter case (question 2), can I use Excel to merge two different measurement.db from 2 different phones, so that I could remove duplicates and manually set if a cell is "new", or "known"?

thank you

**Comment by zamojski** [comment]
Hi, the import/ export works rather like backup / restore, so it overwrites the data.

I don't know if Excel is capable to work with SQLite databases, but if so then you can use it. If you didn't delete (or upload, which also deletes) any measurements you can export them do CSV. This way it would be easier to compare. But in case you want to use SQLite then there's a table called cells which contains a column for discovery date.
