### ISSUE TITLE
Best practices not copyable

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#196]
I'm looking at the Best Practices page that I found in the menus. There is a lot of text on that page. Alas, I can't copy any of it with my finger.

**Comment by zamojski** [comment]
Why would you like to copy that?

**Comment by jidanni** [comment]
Well, for I might want to send it to a friend, without using a wasteful screenshot which takes thousands times more bytes.

Or I might want to quote part of it for a bug report and fix some spellings when I'm doing it. (But not editing the source.)

Or in general I'm just thinking, "Why can't I copy what i see? Is there some security or proprietary problem?... Is it like some website where people are afraid readers are going steal their poetry or something? "

**Comment by zamojski** [comment]
It's just not easy to implement copying from this custom control. Closing as not worth the effort.
