### ISSUE TITLE
Google Earth Pro does nothing when opening this kmz

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#198]
I note that there is some bug in Google Earth Pro on Linux,
when I did Open (CTRL+O) on 2023-03-22-04-06-31.kmz
nothing happens.
So I had to do
zcat 2023-03-22-04-06-31.kmz > x.kml
and then Open on the kml, and then Google Earth Pro reads it OK.
[2023-03-22-04-06-31.kml.gz](https://github.com/zamojski/TowerCollector/files/11034917/2023-03-22-04-06-31.kml.gz)
P.S., I had to cp 2023-03-22-04-06-31.kmz 2023-03-22-04-06-31.kml.gz
to be able to attach it to this issue.

**Comment by zamojski** [comment]
I think this issue should be reported to Google Earth team. On Windows this issue isn't present.

**Comment by jidanni** [comment]
Hmm, I uncompressed the above kml.gz and it opens fine in GEP. So closing.
