### ISSUE TITLE
Easiest upload error to fix ever

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#200]
Here we see a seemingly curious upload error.

The first symptom is the upload seems to be very fast. So many points just take less than a minute:

![Screenshot_20230520_173212_Tower Collector.jpg](https://github.com/zamojski/TowerCollector/assets/1230959/31245f53-d1d7-494b-930b-0a29da6679e6)

The next symptom is this error message we see:
![Screenshot_20230520_173233_Tower Collector.jpg](https://github.com/zamojski/TowerCollector/assets/1230959/cfb7e7fb-bfa0-465a-8197-ec27e9e3e5ec)

Okay, so how to reproduce such a mysterious error?

 Is it very simple:

Just simply forget to have turned on wi-fi, or forget to have turned on mobile data, before starting the upload!

Therefore, before the upload starts, the app should simply test to see if the network is connected, before proceeding to upload!

Then it can just give a much simpler message saying "you forgot to connect to the network first. No internet connection present."

Seen  with Android 13 on a Samsung A13 5G.

**Comment by Espionage724** [comment]
Can apps on Android determine if there explicitly isn't an internet connection? Or do they guess there's no internet connection if they can't reach the server/resource requested?

It sounds like Tower Collector doesn't know there's not an internet connection and fails for reasons not known to it. But can Android tell Tower Collector directly there's no mobile data or not connected to wifi, or let it see those specific states?

If such a check is added, also make sure it works for Android devices connected only on wired Ethernet. Apparently that's a different ordeal and some apps I've seen refuse to try connecting to the internet at all if wifi is off and Ethernet is the only connection.
