### ISSUE TITLE
5g tower is rendered at LTE

### ISSUE THREAD

**Issue by soshial** [zamojski/TowerCollector#207]
![Screenshot_20230703_073618_Tower Collector](https://github.com/zamojski/TowerCollector/assets/100644/6cd8441f-114d-43a7-acfc-adc68d331f5a)

**Comment by zamojski** [comment]
There's not enough information on the screenshot to tell if the cell is the real 5G (SA) or fake one 5G (NSA). The latter is in fact LTE cell using 5G protocols. These may not be correctly reported by Android.

You can check in app's Advanced Preferences if you use Auto or NetMonster API to gather data. These should give the most accurate results.

**Comment by francisuk1989** [comment]
Regarding 5G NSA they dont broadcast a Cell ID like LTE/3G etc and only PCI.
