### ISSUE TITLE
add Package setting to be able to broadcast data to other (inactive) applications

### ISSUE THREAD

**Issue by se-ti** [zamojski/TowerCollector#208]
I'd like to use your app to collect data to build a mobile network coverage map.

TowerCollectors' MEASUREMENTS_COLLECTED notifications are great for it, but according to contemporary Android Policies (prohibited implicit broadcast receivers) they won't wake up inactive application. 
https://developer.android.com/about/versions/oreo/background#broadcasts

Could you please add externPackageID setting and a couple of lines 
```java
intent.addFlags(Intent.FLAG_INCLUDE_STOPPED_PACKAGES)
if (!TextUtils.isEmpty(externPackageID))
    intent.setPackage(externPackageID);
```

here
https://github.com/zamojski/TowerCollector/blob/7315e1f3c04e80867712467e052f08c6e29b4c01/app/src/main/java/info/zamojski/soft/towercollector/broadcast/ExternalBroadcastSender.java#L42C66-L42C66

**Comment by zamojski** [comment]
@se-ti What's an `externPackageId`?

**Comment by se-ti** [comment]
I thought this could be a setting string (for example, somwhere by the existing switch Collector / Notify about collected measurements), where the user can add package id (like com.example.datagatherer) of the application, he wants to notify.

Btw, i've read some more specs since july, and i'm not sure even intent.setPackage would help :(
Probably there exists one more limit: implicit broadcast receivers work just between apps, signed with the same certificate. 
But this should be tested.

**Comment by zamojski** [comment]
Can you share some articles? From what I found there shouldn't be any issues except for missing `intent.addFlags(Intent.FLAG_INCLUDE_STOPPED_PACKAGES)`.

**Comment by se-ti** [comment]
As far as i understand, 

1. to be activated (launched if it's not yet launched) by extern intent, the app should declare broadcast receicer in it's manifest.
2. since Android 8 applications [can no more subscribe for implicit events](https://developer.android.com/about/versions/oreo/background#broadcasts), except for closed (and irreleveant) [white-list](https://developer.android.com/guide/components/broadcast-exceptions)
3. Dev android.com: An [explicit intent is one](https://developer.android.com/guide/components/intents-filters#ExampleExplicit) that you use to launch a specific app component... 

https://stackoverflow.com/a/46121548/7867704
If the Intent has a ComponentName, [the Intent is explicit](url). Otherwise, it is implicit.
ComponentName... ...can be derived by the system from the action string, etc. plus the package defined via setPackage()

That's says me, you need setPackage to wake up another app with a specific intent.

P.S. The idea of common certificate goes from https://developer.android.com/about/versions/oreo/background#services `Broadcasts that require a [signature permission](https://developer.android.com/guide/topics/manifest/permission-element#plevel) are exempted from this restriction, since these broadcasts are only sent to apps that are signed with the same certificate, not to all the apps on the device.`
and seems to be irrelevant.

**Comment by zamojski** [comment]
I don't declare any `<permission>` in the app. My broadcasts are not protected this way so I don't think it's the case.

It may be truth that some configuration is missing but instead of `setPackage` I think we need to set the exact class and package name - https://stackoverflow.com/a/62891524

Can you share the code you use to receive the intent in your app?

**Comment by zamojski** [comment]
I've made a test in couple of scenarios:
1. Two apps each signed differently on Android 10 phone - broadcast works fine, even without `Intent.FLAG_INCLUDE_STOPPED_PACKAGES`.
2. Two apps signed with the same key on Android 12 phone - broadcast works fine.
3. Automate app from Play Store and one my own that received fake broadcast on Android 13 emulator - broadcast works. In Automate I just set the action and extras fields for Broadcast send action.
4. Listen for broadcast from Tower Collector in Automate - broadcast was never received.
5. Listen for broadcast from Tower Collector in my own app - broadcast was never received.

This brings the conclusion that something is indeed wrong but no idea what...

**Comment by zamojski** [comment]
@se-ti Are you still facing the issue?

**Comment by se-ti** [comment]
Hi Adam!
No, i gave up the idea of collecting data via your app indirectly.
Just did it directly with your app.

Even though, since OpenCellId has silently changed their archive policy, it seems to be a good idea to store collected data on premises. Not just upload them to openCellId.

https://community.opencellid.org/t/actual-data-export-policy-are-old-contributions-removed-or-just-not-exported/1318/2
https://community.opencellid.org/t/why-does-the-full-database-file-have-much-less-data/1311
https://community.opencellid.org/t/is-there-a-reason-why-cell-towers-csv-gz-file-size-has-decreased-so-much-compared-to-before/1303/5

**Comment by zamojski** [comment]
Personally I export all measurements I collect to CSV file. Then I have a script to merge all such files into 1 year large archive which is quite big (335 MB uncompressed for 2019) but to be honest I didn't run it for last 3 years but the "partial" files are still there :D

Regarding OCID they don't solve issues quickly and you have to remind them from time to time to check if anything has changed. Still better that Mozilla which didn't even reply to my emails for couple of months... However as a software developer I understand they reasoning - providing such huge dump packages can cost a lot of money spend on traffic. One day I had an idea to setup my own project of that kind but the of maintaining terabytes of data and lots of traffic would be too high for a single person.

For now I'm closing the issue as obsolete.
