### ISSUE TITLE
Get cell info even when no GPS is active

### ISSUE THREAD

**Issue by michalisk13** [zamojski/TowerCollector#213]
Hi,

I want to be able to get cell information even when there is no GPS signal.
Can you guide me where I need to look?

Thanks,
Mike

**Comment by zamojski** [comment]
Hi, there's no such possibility in Tower Collector. I suggest using [NetMonster](https://play.google.com/store/apps/details?id=cz.mroczis.netmonster) or [Network Cell Info](https://play.google.com/store/apps/details?id=com.wilysis.cellinfolite) for that purpose.

**Comment by michalisk13** [comment]
Hi,

Thanks again.

BR,
Mike
