### ISSUE TITLE
SIM-less operation

### ISSUE THREAD

**Issue by nebukadnezar** [zamojski/TowerCollector#218]
Does the app work without a SIM card in the phone? Considering a SIM less phone is able to make emergency phone calls, it still registers on the network, so in theory that should still be able to extract CID/LAC|TAC/MNC/MCC?

**Comment by nebukadnezar** [comment]
Got that tested and confirming it doesn't work without a SIM.

**Comment by zamojski** [comment]
In practice it depends on the phone. I have a couple of old ones which report only main cell tower without neighboring cells. But generally there's no way to determine it globally, you need to test separately on each device.
