### ISSUE TITLE
Feature request: timed eSIM swap

### ISSUE THREAD

**Issue by nebukadnezar** [zamojski/TowerCollector#219]
for those of us operating with multiple SIMs (or eSIMs even) it would be a great feature for this software to switch networks on a predetermined schedule, say every 30 or 60 seconds, then fetch the cell tower data, store it, and move to the next SIM.

**Comment by zamojski** [comment]
Changing SIM cards is not supported in Android - there's no such method, even hidden. I read years ago it was possible on some phones using root, but that's not something I'm going to try myself and support later.

Generally Android provides cell tower info for all SIM cards, so I don't see a reason to implement such feature.

**Comment by nebukadnezar** [comment]
Great, thanks for that info, didn't know that eSIMs couldn't be switched programmatically. And yes I fully agree with not supporting rooted device features. The Galaxy S23 I bought for the purposes of running your software only gives cell info for the currently active SIM (i.e. it doesn't run the second eSIM in parallel). My iPhone can do that, I have several eSIMs on that and I always have two operating in parallel, very useful when travelling in remote areas where not all providers always have service.
