### ISSUE TITLE
Apply theme without restarting the app

### ISSUE THREAD

**Issue by zamojski** [zamojski/TowerCollector#22]
Apply theme without restarting the app, now you need to restart the app to change color theme.

**Comment by zamojski** [comment]
After investigation it turned out that the implementation requires too many hacks inside the application to properly handle all possible cases. Android stacks activities without providing option to alter previously opened. Complete activity stack needs to be re-created from scratch and this will bring a lot of complexity to the app and the benefit will be relatively small.

**Comment by asl97** [comment]
how about automatically restarting the app on theme change and directly open the theme page when it start up?
