### ISSUE TITLE
timed eSIM cycling - take two

### ISSUE THREAD

**Issue by nebukadnezar** [zamojski/TowerCollector#220]
Hello again - it just occurred to me that there must be a way to do this. I'm using two providers who have Apps that install their eSIMs programmatically and activate them (and switch them active by doing so). So there must be a way to do this through an official API. Both Airalo and Telstra in Australia have Apps that do this.

Could you please take another (deeper) look at possible ways how this could be supported?

Thanks!

**Comment by nebukadnezar** [comment]
Thank you, I really appreciate you taking the time to look into this. What you found I guess makes sense.

The reason for wanting this feature is simple: We have 3 providers of physical infrastructure in Australia. With 3 eSIMs and swapping two of them in 30s intervals you can map the entire mobile infrastructure around you with a single device in a single go. This weekend for instance I'm going to be driving about a 2000km around locations where we sample mobile tower cell IDs using srsRAN (receive only as those are radio sensitive areas) to help understand peculiar propagation effects where despite being in a radio quiet area we often detect mobile towers, some from very far away. But those close by I don't have data on (because nobody probably ever drove through that area with a cell mapper enabled).

**Comment by rgrind** [comment]
Get a cheap "test phone" for your 3rd SIM.

**Comment by nebukadnezar** [comment]
That's exactly what I just decided to do. :)

**Comment by nebukadnezar** [comment]
The Pixel does - it's MEP capable and can run two eSIMs simultaneously. Works a treat! The Samsung S23 can't do MEP and thus only reports a single carrier at a time. Just uploaded 36000 cell measurements from today (total from both phones).

For my own use btw you might be interested to know I'm reading the exported sqlite db directly. I'm not sure why the export function for the database is separate from the CSV etc. export functions?

**Comment by zamojski** [comment]
> For my own use btw you might be interested to know I'm reading the exported sqlite db directly. I'm not sure why the export function for the database is separate from the CSV etc. export functions?

The database export is a function you can use to migrate to a new phone or just backup your data and statistics. It's not intended to be used by "regular" users as the data structures can change at any time.

**Comment by zamojski** [comment]
Closing as resolved.
