### ISSUE TITLE
OCID upload failure

### ISSUE THREAD

**Issue by JonnyTech** [zamojski/TowerCollector#226]
This has been happening all day on various different networks  so contacting you as per the message request

![Screenshot_20240624-182427](https://github.com/zamojski/TowerCollector/assets/3584732/95306386-02b5-4888-a526-e11e1cbb5f58)

Latest version from Fdroid on Android 13

**Comment by paveldenton** [comment]
the same

**Comment by zamojski** [comment]
The OCID service returns `Invalid file format.`. I've contacted them to resolve the issue as nothing has changed on Tower Collector side. I'm waiting for reply, most likely tomorrow.

**Comment by JonnyTech** [comment]
Yay, it's working again. Thank you.
