### ISSUE TITLE
where has measurements.db gone?

### ISSUE THREAD

**Issue by nebukadnezar** [zamojski/TowerCollector#227]
Hi,

haven't used the app since March. Did a big survey yesterday and was expecting to find the measurements.db file I've used in the past to import data in /storage/self/primary/android/data/info.zamojski.soft.towercollector/files (where I think it used to be).

Has that been moved elsewhere? Can't seem to locate it.

Even when exporting CSV data, I can't find the location where towercollector is writing the data to. Help for this old brain would be much appreciated, thanks!

**Comment by joelkoen** [comment]
You can select where files are exported to in Settings -> General -> Change storage location

**Comment by zamojski** [comment]
The `/storage/self/primary/android/data/info.zamojski.soft.towercollector/files` is the place where Android stores app's internal files, like cache. I believe it's protected by the system somehow but it never exposed the database.

I would rather look for `/storage/emulated/0/TowerCollector` or similar.

**Comment by nebukadnezar** [comment]
Got it, thanks guys! I forgot I needed to export the database first. Duh. Found it after that in storage/emulated/0/Documents.
