### ISSUE TITLE
Provide option to contribute to Mozilla Location Services

### ISSUE THREAD

**Issue by zamojski** [zamojski/TowerCollector#23]
Provide option to contribute to Mozilla Location Services through upload and JSON file.

**Comment by Gitschubser** [comment]
http://wiki.opencellid.org/wiki/Main_Page

**Comment by zamojski** [comment]
I've seen the announcement, it's a pity that the project may die after so many years... I will work on MLS integration as a first priority as soon as I find a bit of free time (now fully loaded with personal matters).

**Comment by takiainen** [comment]
why not targeting radiocells.org too? It seems more open than MLS.

**Comment by zamojski** [comment]
I will take it into account, thanks!

**Comment by kevin-brown** [comment]
I'm just going to note that MLS and OpenCellID share the same data format (this was intentional).

Openbmap (radiocells.org) is using an XML file for exports, using a format which I don't fully recognize.

**Comment by zamojski** [comment]
I don't think this is an issue unless the format is not documented.

**Comment by zamojski** [comment]
Option to export to MLS JSON format will be available soon in the app. I'm thinking of good way to implement the upload directly so it will not interfere with OCID. Stay tuned :)

**Comment by zamojski** [comment]
Available in version 2.0.0.
