### ISSUE TITLE
Two towers on either side of a wall

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#234]
Try this experiment: stand next to a tall wall. Start the app, and look at the Last Collected screen. Note the cell id. Now go to the other side of the tall wall. The problem is there is a different cell tower on the other side of the wall but because the GPS is in the exact same position so the program doesn't record a second cell tower. I'm not sure how to solve this problem the best way for this app. Or maybe this is just a special case.

**Comment by joelkoen** [comment]
Cell towers don't provide enough accuracy to consistently estimate the user on one side of a wall in situations like this, so I don't think this is a big issue.

**Comment by rgrind** [comment]
GPS shouldn't matter. At any point in time your mobile will likely be
seeing multiple towers. Your mobile's modem will connect to the "strongest"
one. That is that TC reports. If you to where other tower is stronger (eg
other side of wall), eventually your mobile will connect to that tower, and
then TC will report that one. TC doesn't report on "neighboring"
(unconnected but visible) towers, AFAIK.

**Comment by zamojski** [comment]
Whenever Tower Collector detects change of any of main cells (not neighboring because then change very often) the new measurement is created regardless if the device has moved or not. Try changing network type without stopping collection and you'll see it happening.

**Comment by jidanni** [comment]
All I know is I was standing still, and the last saved page said "Tower A, 2 seconds ago." 

But then all the other apps said my main tower is now Tower B, but the last saved page didn't change. 

Maybe it had to do with recently recording Tower A also at that same position.
