### ISSUE TITLE
support BeaconDB

### ISSUE THREAD

**Issue by secretmango** [zamojski/TowerCollector#237]
Hey there! Awesome app!

I have contributed a ton of towers already.

https://beacondb.net/

Seems to be the successor to MLS. 

Their guide says:

> in Upload Preferences, enable support for custom MLS services and set the address to https://beacondb.net/v2/geosubmit

Having this by default would be great!

**Comment by secretmango** [comment]
I suppose this would mean reverting some commits that added the popup banner and blocked MLS upload, and changing the URL.

**Comment by zamojski** [comment]
I'm working on it :)

Related to #223 and #228

**Comment by zamojski** [comment]
Implemented in 2.15.0, will be available in all stores within couple of days.

**Comment by zamojski** [comment]
Maybe a bit later because Google wants some additional information from me before publishing the app update... and there's an build issue in F-Droid.
