### ISSUE TITLE
jcenter shutdown

### ISSUE THREAD

**Issue by licaon-kter** [zamojski/TowerCollector#239]
ref: https://jfrog.com/blog/jcenter-sunset/

ref: https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/8413917577#L318

**Comment by licaon-kter** [comment]
Sure, clean your gradle cache, and retry.

Does it still work?

**Comment by zamojski** [comment]
Addressed in version 2.15.1
