### ISSUE TITLE
2.15.x permission denied errors when starting collector

### ISSUE THREAD

**Issue by foundObjects** [zamojski/TowerCollector#242]
Since 2.15.x I've been unable to start the collector without receiving permission denied errors:

![Screenshot_2024-12-01-19-20-02-88_2f3dadf9fbb0690dd1aedd8395bf8072.jpg](https://github.com/user-attachments/assets/7d47ddf1-cde1-4bf7-9aeb-ed6f9d67cc4d)

I've had to revert to 2.14.x to do any collecting at all.

Nothing has changed on my device between 2.14 and 2.15, permissions are all granted as expected and everything works properly on 2.14.x:

![Screenshot_2024-12-01-19-20-24-61_ab1359306de43320f9557c797b1c4be5.jpg](https://github.com/user-attachments/assets/82f39579-73a2-459e-aa3e-851b62551095)

Affected device: OnePlus 9 Pro, running Android 13 (last available OOS android 13 build.)

**Comment by zamojski** [comment]
Will be fixed in 2.15.4.

**Comment by foundObjects** [comment]
Thanks, that did it.

Cheers!
