### ISSUE TITLE
Upload result "Expected URL scheme 'http' or 'https' but no scheme was found for

### ISSUE THREAD

**Issue by skinkie** [zamojski/TowerCollector#246]
Just updated Tower Collector. Upload gave:

"Upload result "Expected URL scheme 'http' or 'https' but no scheme was found for"

**Comment by skinkie** [comment]
It seems that "Use custom BeauconDB service" is by default on.

**Comment by zamojski** [comment]
It's not enabled by default - `<bool name="preferences_custom_mls_enabled_default_value">false</bool>`. However if you enabled it they it will stay enabled until you disable it.

**Comment by skinkie** [comment]
@zamojski I don't recall ever to have it enabled. Bu maybe you can add a check if the value is undefined, and not try it or raise a warning?
