### ISSUE TITLE
NR cells not sent on custom service

### ISSUE THREAD

**Issue by RealTux678** [zamojski/TowerCollector#247]
Hi,
I realize that NR cells are not sent when using the "MLS compatible" personalized server function.

During sending, the counter decrements on app, but on server side I receive an empty array "{items:[]}".

Sending to OpenCellId is ok.

**Comment by zamojski** [comment]
The original MLS project didn't support 5G networks at all, so these were cut out... and looking at the code these are still skipped while uploading.  I will change it in the next update. Thanks for pointing this out!
