### ISSUE TITLE
Option to capture signal -XX or below

### ISSUE THREAD

**Issue by francisuk1989** [zamojski/TowerCollector#248]
I would like to see a option to capture all signals **-72** or below or ask a user to set a number 👍

**Comment by zamojski** [comment]
What would be the purpose of such feature? Please share some detail.

**Comment by francisuk1989** [comment]
> What would be the purpose of such feature? Please share some detail.

Only record/collect that a tower was near by.

**Comment by zamojski** [comment]
I doubt if this is the right method as signal strength may significantly vary between phones and also depends in the nearby buildings.

**Comment by francisuk1989** [comment]
> I doubt if this is the right method as signal strength may significantly vary between phones and also depends in the nearby buildings.

Not a problem, It was just an idea for a option for them who wonts to enable this feature.

**Comment by zamojski** [comment]
Every idea requires time for implementation, so I don't consider it for the near future.

**Comment by francisuk1989** [comment]
Thanks for keeping the project live.
