### ISSUE TITLE
Release 1.14 lacks APK

### ISSUE THREAD

**Issue by IzzySoft** [zamojski/TowerCollector#30]
The latest release (tag: `1.14.0`) unfortunately lacks the `.apk` file (probably forgotten). Could you please attach it? Thanks in advance!

**Comment by zamojski** [comment]
Sorry, I forgot to add it here. Now it's in place.

**Comment by IzzySoft** [comment]
Boah – that was fast, thanks a lot! Just kicked my updater to grab it immediately, update is rolling out right now (update: rollout completed).

PS: Cool app – and I'm very glad I now can update it without having to check Playstore manually :innocent: Be welcome to add a link to its new repo-place in your `README.md` next to the Playstore one :stuck_out_tongue_winking_eye:
