### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Poussinou** [zamojski/TowerCollector#31]
Hi,

I would like to translate this app in French to help people join this project.
But there are a lot of files [there](https://github.com/zamojski/TowerCollector/tree/master/app/src/main/res/values). Which ones should I translate exactly (other than the strings.xml file)?

**Comment by zamojski** [comment]
Hi, I used to have a dedicated tool for translators but I didn't update it for very long time. The number of files is quite large, you can find them in strings, arrays, permissions, preferences, info in mentioned directory as well as all html files in raw directory in resources... I know it will take long hours to begin bit if you're ready to spend such amount of time please let me know. If you'd like to use a tool for this purpose please also mention this and I will spend some time to recover it ;-)

**Comment by Poussinou** [comment]
Hum it makes a lot of files indeed. I'm ready to spend such amount of time, because I really think that we can see more persons joining the project of collecting datas if everything is available in their own language, specially for people who don't know anything about programming or even English...

I'm used to Crowdin and Transifex (I really prefer Crowdin, and it's free for open-source projects like this one). But I do not know if it's worth spending time to set up a complete Crowdin page for this project just to collect translations regarding the huge amount of files to upload... However, when it's done, you can use a bot to upload the new strings to translate on Crowdin I think, and another bot to import the translated strings from Crowdin to Github.

I already contribute a lot on both platforms, just ask if you have any questions :) And by the way, I can also contribute the files one by one without Transifex or Crowdin, it just will be harder but that's ok, I'm also used to this kind of way to translate^^

**Comment by zamojski** [comment]
@Poussinou I decided to recover my old translation tool - OneSky because quite a lot of other languages has been translated there and just require some update. Please go to http://i18n.zamojski.info/ and log in there. Once I receive your request for access I will grant you necessary permissions.
