### ISSUE TITLE
export fails, claiming to be unable to create a directory

### ISSUE THREAD

**Issue by IzzySoft** [zamojski/TowerCollector#34]
I just tried to export data I've collected today during an excursion. This was the first time I used this functionality on that device. TC triggered the permission dialog, I granted (looking into *Apps › Tower Collector › Permissions* confirms this) – and got a toast informing me "Export failed, directory could not be created".

Unfortunately, there's no setting where I could specify a directory. Neither does it tell me where it wanted to create one, so I could not do that by hand.

So where to look for and create it – and then, how to fix this issue?

LG P880 running Android 6.0.1 (inofficial LOS). TC installed from the Github releases (via my repo).

**Comment by IzzySoft** [comment]
OK, managed to work around by doing an `adb backup` of apk+data and restoring that on a second device. Performing an export there told me the directory:

`/storage/emulated/0/TowerCollector`

Created that directory on the first device (via ADB), and after that the export succeeded. Unfortunately I didn't consider checking logcat when it failed, and the buffer on that device seems to be too small so there's nothing in there now.

**Comment by zamojski** [comment]
For some reason the app was unable to create the directory you've mentioned. The folder is accessed by official Android API so it should be available. I would say this is rare error caused usually by some custom ROM. I will close the issue as it's not reproducible on most devices.
