### ISSUE TITLE
EARFCN not logged

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#36]
The EARFCN is available from the system but not logged anywhere.

**Comment by zamojski** [comment]
What's the value added for the user if it will not be used by OCID or MLS?

**Comment by jidanni** [comment]
Let's not throw away data just because some websites didn't think it was
available yet perhaps.

Anyway for the user trying to understand his local network it is very
important.

If you think about it one must have a frequency before one can have any
of the rest.

Also e.g., frequencies change more than MCC, MNC but less than the rest
of the items, so they are just as valuable...
