### ISSUE TITLE
Add newline after each JSON record

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#37]
Are you sure the json files produced are valid?
```
garbage after JSON object, at character offset 152475
(before ""items":[{"timestamp...") at /usr/bin/json_pp line 40.
```
https://stackoverflow.com/questions/38088384/can-a-json-file-contain-more-than-one-object
https://forums.pentaho.com/threads/136651-How-to-process-a-JSON-file-with-multiple-records/
OK, at least put a newline after each record.
Here is the workaround I used to create several json files.
```
perl -pwle 's/{"items":/\n$&/g' 2018-04-24-17-29-12.json |
sed /^$/d | split --lines=1 --additional-suffix=.json
```

**Comment by zamojski** [comment]
I noticed just few days before you reported that sometimes json gets corrupted by two root elements. I didn't find yet a way to reproduce the issue but I will take a closer look at this. Thanks!
