### ISSUE TITLE
GPX data: offer to "Share" or open with other app

### ISSUE THREAD

**Issue by IzzySoft** [zamojski/TowerCollector#40]
Currently it's possible to save collected data to GPX. Would be nice to also directly open the exported file with another application, e.g. [Location Map Viewer](https://github.com/k3b/locationMapViewer), to display the track on a map. LMV even accepts GPX data via intent, but also seems to have registered for the file type: I used a file manager to navigate to the exported `.gpx` file, and tapping it opened LMV. Other apps might offer the same.

**Comment by kolesar-andras** [comment]
Replace `keep` button with `share`, see #66. Popup could be closed with `back` button.

**Comment by zamojski** [comment]
I think it does exactly what you've asked for. You'll be able to use Share button instead of Keep at the export finished screen, like on the screenshot. This will use standard Android sharing function so any app compatible with the file format can handle it (at least in theory).

![obraz](https://user-images.githubusercontent.com/12007817/91091427-d8f91580-e656-11ea-9746-7fd74925c7be.png)

**Comment by IzzySoft** [comment]
Oh – yes, definitely! I was just wondering the other issue was kept open; doesn't this solve #73 as well?

**Comment by zamojski** [comment]
It is resolved, I thought I closed both with that commit comment but it closed only the first one, thanks for pointing this out :)

**Comment by IzzySoft** [comment]
Gladly – and thanks again for implementing it! Could have used it today to get my yesterday's mappings into OsmAnd for navigating the same track reverse :rofl:

(a pity that the LocalGSMBackend for UnifiedNlp doesn't accept "uploads" this way. So I have to wait until my mappings are downloaded from OpenCellID again instead of having them available instantly…)

**Comment by jidanni** [comment]
Nice photo, but what if one doesn't want to do any of "upload delete share"?
OK, he should just hit the Android "Back" button.
That will do the same as the previous Keep option (i.e., do nothing further, just get rid of the asking screen,) but don't you think he should have a more clear way of getting out of the three choices other than having to try the Android Back button?
OK, "Keep" involves more thinking than just an "X" closer button at top of the block. So how about adding an X closer button?

**Comment by zamojski** [comment]
Then one can just uncheck Share and the Keep button will appear instead.

Have you ever seem the X button on Android (except for ads)? I don't think this is the way to go on mobile device. Meanwhile I have added the forgotten cancellation with back button and when touched outside of the window.

**Comment by IzzySoft** [comment]
"You cannot please all the people all the time. And yesterday, all those people have been in my show…" (I just cannot remember who said that)

I'd say the current variant as shown in above screenshot is fine, thanks a lot! Cannot wait seeing it on my device :smiley:

**Comment by zamojski** [comment]
I will publish it most likely this week :) I hope it will work fine for GPX and other apps - you will need to select just GPX as the format to get the shared file type reported correctly. Meanwhile I'm working also on #21 but this will take me a couple of weeks more.

**Comment by IzzySoft** [comment]
> you will need to select just GPX

that's my setting anyway, thanks!

> Meanwhile I'm working also on #21

Wow, that's cool! And yes, clearly that takes some more effort. Fingers crossed, and thanks again!

**Comment by IzzySoft** [comment]
Btw: I wonder what is shared here. Today I exported my collection as GPX. Afterwards I gave the new share button a try. I have 2 apps that can deal with GPX data – none of them showed up (but a couple of others I'd count as unrelated – yeah, I could share the file via mail or chat, but that's not what I intended: I wanted to share it to a "map display" like OsmAnd or Location Viewer). When I tap the GPX file in the file explorer, both are shown as possible targets. Any idea what could be wrong here?

**Comment by jidanni** [comment]
https://play.google.com/store/apps/details?id=uk.co.ashtonbrsc.android.intentintercept can help you figure it out, @IzzySoft .

**Comment by IzzySoft** [comment]
@jidanni I'm not using Play anymore, don't even have an account there (Google canceled mine for inactivity already a while ago). And my point is less what format it is shared in, but rather if the saved file could be shared so those apps get triggered. Doesn't help me if I'd knew it's shared as X as that doesn't make it open as GPX in my case :wink: But thanks!

**Comment by jidanni** [comment]
OK, but anyway F-droid has newer https://github.com/k3b/intent-intercept .

**Comment by zamojski** [comment]
I've checked and I confirm the issue with GPX/KML/KMZ occurs. Thanks @jidanni for the links, it was helpful. I think I know what makes the difference but I need to do several trials to fix it.

**Comment by IzzySoft** [comment]
Thanks to both of you! @zamojski I'll test as soon as the update is there and report back here then. And it's ready when it's ready, I'll stay patient :smiley:

**Comment by zamojski** [comment]
What I discovered is that OsmAnd/OruxMaps react on VIEW action which works like opening the file, not sharing. So in the end the sharing works as intended but you ask for the open function which can work for a single file only. I will make some adjustments in the app to allow these 2 options independently.

**Comment by IzzySoft** [comment]
Oh – I wasn't aware of that (maybe we should file an issue with OsmAnd then for this – or does it make no sense as sharing might not work this way with them? I've no idea of the internas). Thanks for establishing a "work around"!
