### ISSUE TITLE
For 4G LTE networks only the long CellID is shown

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#45]
For 3G networks the Last Saved window shows both the cell ID and the long cell ID. However for 4G LTE networks only the long CellID is shown. Also it is just called CellID.

**Comment by zamojski** [comment]
Do you have any resource confirming that Long CID is used by LTE networks because I couldn't find one?
On [Wikipedia](https://en.wikipedia.org/wiki/Cell_ID) you can find only the info for UMTS networks.

**Comment by jidanni** [comment]
All I know is I had to write a program to convert those long IDs to something I could make sense of
```
$ echo 106886925 | cellid4G
106886925: 417527-13
```

[cellid4G.txt](https://github.com/zamojski/TowerCollector/files/2407833/cellid4G.txt)

**Comment by jidanni** [comment]
If you install e.g., https://play.google.com/store/apps/details?id=com.parizene.netmonitor I'm hoping to see the same numbers it shows.

**Comment by zamojski** [comment]
I'm not really convinced that this app shows correct results. I was looking at technical standards for LTE when I was implementing the change for UMTS but wasn't able to find similar rule in LTE reference document.

**Comment by jidanni** [comment]
https://www.cellmapper.net/enbid?net=LTE&cellid=106886925
I want to see the
```
eNB ID	417527
```
and show it as 41-7527.

See also
https://github.com/mozilla/ichnaea/issues/501
https://github.com/mozilla/ichnaea/issues/415
