### ISSUE TITLE
Oreo adaptive icon shape

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [zamojski/TowerCollector#48]
Please add support for icon shape
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html
https://material.io/guidelines/style/icons.html

you should fix it to upload new version to google play
https://www.xda-developers.com/google-play-app-updates-must-target-android-8-0/

**Comment by zamojski** [comment]
Starting from version 2.0.0 the app targets Android 8.0.

The adaptive icons require more time than I have currently but I will take care of this later.

**Comment by c-e-p-x-u-o** [comment]
It's easy. Just keep the central tower and add the background.

**Comment by zamojski** [comment]
Do you know maybe a good converter between svg and Android xml? The one in Android Studio doesn't respect line thickness.

**Comment by c-e-p-x-u-o** [comment]
You'd like to say it's impossible to use svg directly?

**Comment by zamojski** [comment]
No, they format is very similar but not exactly the same.

**Comment by c-e-p-x-u-o** [comment]
Looks nice. Thank you!
Have you found svg -> xml converter?

**Comment by zamojski** [comment]
Not really, I had to convert every single object to path and then adjust the sizes according to adaptive icons guidelines which took me around 2 days but finally the icon looks nice :)
