### ISSUE TITLE
Upload Button dangerously placed, should offer confirmation option

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#51]
I hate to say it but the Upload Button is so close to the ON/OFF button,
and also the menu, that the user is very likely, sooner or later, to
accidentally touch the Upload Button, sending his precious data to
upstream, and deleted from his device, before say, he has a chance to
save it to GPX etc. first, whatever.

In fact one might say to only safe way to use the app is when in
Airplane Mode, when an accidental tap of the Upload Button will fail.

One might say "who cares, your data is now upstream." But in fact it is
very hard to retrieve ones data back from the two current upstream
locations.

Therefore perhaps there should be an option:

[ ] Ask for confirmation when hitting the Upload Button

**Comment by zamojski** [comment]
There's such option available since version 2.0.0. If you go to app preferences->Upload->Show configurator.

**Comment by jidanni** [comment]
There is a big problem there!

It says "Show configurator" with a switch.
When the switch is off it says "Upload will use the below settings."

When we turn it on, the below settings still stay there (not becoming
grey).

Therefore the switch seems not to make sense.

OK when switched on it says "configuration window will be shown before
each upload". OK that is apparently what I want... but it is saddening
that each button must be toggled to reveal what the other choice is...
we can't just see them all and pick a radio button...

Anyway the words "Upload will use the below settings" should certainly
be changed to "Don't show configuration window before each upload".

**Comment by zamojski** [comment]
The main purpose of show configurator is to allow use customize the settings before each upload, these choices are preserved as regular settings which you see in preferences. If configurator is switched off it will use what's defined below, otherwise values below act as default / recently selected values. You need to at least once select what you want to do on upload, later below settings will be used.
