### ISSUE TITLE
When uploading to both sites, the notification says only one is successful

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#57]
When uploading to both sites, the notification says only one is successful (only mentions one), but the toast message says both are successful.

**Comment by zamojski** [comment]
Looking at the code I don't see it possible... See the following lines in [UploaderService.java](/zamojski/TowerCollector/blob/master/app/src/main/java/info/zamojski/soft/towercollector/UploaderService.java) in which the toast gets exactly the same message to show.
```
        String ocidMessage = getString(getMessage(ocidUploadResult));
        String ocidDescription = getString(getDescription(ocidUploadResult));
        String mlsMessage = getString(getMessage(mlsUploadResult));
        String mlsDescription = getString(getDescription(mlsUploadResult));
        String message = getString(R.string.uploader_result_message, ocidMessage, mlsMessage);
        String description = getString(R.string.uploader_result_description, ocidDescription, mlsDescription);
        Toast.makeText(this, message, Toast.LENGTH_LONG).show();
        // update notification according to result
        Notification notification = notificationHelper.updateNotificationFinished(message, description);
notificationManager.notify(NOTIFICATION_ID, notification);
```

Does it happen every time? Do you have a log file from that moment?

**Comment by jidanni** [comment]
Maybe there is a height limit on one but not the other, so the user only sees, or notices, less on one.

**Comment by zamojski** [comment]
Which Android version your phone is running?

**Comment by zamojski** [comment]
If you have non-standard Android like Xiaomi MIUI you may experience such issue because it doesn't allow notifications to expand and thus limit the max length of the message. There's nothing I can do about it as a developer.

**Comment by jidanni** [comment]
Asus ZenFone3 Android 8.0. All I know is in e.g.,
https://stackoverflow.com/questions/9487223/what-is-the-maximum-number-of-characters-that-can-be-displayed-in-android-and-io
he says his experiments on Samsung give Title: 16 chars Text: 27 chars.

**Comment by zamojski** [comment]
I think in reality there're many more parameters that influence number of characters, for instance font used by manufacturer or set by the user, font size which can be modified by the user, as well as the screen size and its density.

**Comment by jidanni** [comment]
All the more reason to play it safe, with one short line that says it all.
