### ISSUE TITLE
wrong number of measurements to upload

### ISSUE THREAD

**Issue by kolesar-andras** [zamojski/TowerCollector#59]
Version 2.0.5 shows only a small fraction of local measurements to be uploaded. Screenshot below shows 32971 measurements but only 4487 of them are counted to be uploaded. CSV export has 4500 lines, they seem to be the first ones in time.

![Screenshot_20190703-132457](https://user-images.githubusercontent.com/10164425/60588517-716b7100-9d97-11e9-8920-e51c0a04b3ea.png)

Version 2.0.2 works fine. Not tested intermediate versions but I think 2.0.3 can be the first affected because there was a change in DB schema.

**Comment by kolesar-andras** [comment]
I have made a backup from database and checked tables. Table `measurements` has 4487 entries, `cell_signals` has 32971. Upload seems to handle this new 1..n relation correctly, but export fails to retrieve all measurements.

**Comment by zamojski** [comment]
I'm aware that this issue occurs for export, I just didn't have time to check it. Thanks for sharing your results of investigation. I will take a look at it soon.

**Comment by zamojski** [comment]
There are actually 3 issues, I think I fixed 2 of them but I need to test them. The related issue #60 is more complicated.
