### ISSUE TITLE
add confirmation dialog before clearing all data after exporting

### ISSUE THREAD

**Issue by kolesar-andras** [zamojski/TowerCollector#61]
When I tap Menu / Clear all there is a confirmation dialog:

> Clear all data  
> Are you sure you want to permanently remove all locally stored data?

After exporting data on *export successful* dialog there is no such dialog when I hit *delete* button. This button is close to *upload* and *keep* buttons therefore I have great chance to tap it.

I have lost opportunity to upload 25 thousand measurements because I have touched *delete* on a faulty touch screen. My use case: export into local file and upload. In this case I was not able to upload.

**Comment by zamojski** [comment]
Personally I don't like the design of this screen since beginning but nothing better and easy to code come to my mind at that time. I will try to improve it.
