### ISSUE TITLE
use consistent verbs for deleting data

### ISSUE THREAD

**Issue by kolesar-andras** [zamojski/TowerCollector#62]
Currently there are three synonyms for the same task:

* Clear (in main menu)
* Remove (in confirmation dialog)
* Delete (in export successful dialog)

I think using only one verb consitently would be better.

**Comment by zamojski** [comment]
The clear option in main menu has a bit different function - it clears completely all statistics, previously discovered cells, etc., basically all local data. Regarding Remove and Delete you're right as they do the same.
