### ISSUE TITLE
Improve on / off button

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#64]
The square versus circle on off button has to go. Because they look so much like each other. And also many users assume the app is already on the minute that you touch its icon in the launcher.  Please at least color the inside of the button red versus green. You might say that it's easy to remember square versus circle and many other apps use it. But no other apps on my phone use it. Therefore even after a few weeks of not using it, one forgets the difference.

**Comment by jidanni** [comment]
One only notices that it's actually not recording when the last saved page is only showing last weeks savings, even though the app has been on for many minutes.

**Comment by zamojski** [comment]
In my opinion colorful buttons may reduce readability depending on theme selected by the user. Moreover Android Material Design guidelines say the icons must be either white or black and the upcoming Android Q introduces automatic selection of themes depending on preferred configuration. See https://developer.android.com/preview/features/darktheme

**Comment by jidanni** [comment]
OK but looking at that page it still seems you are not using standard buttons.
Apparently "run" should be something like
U+25B6 BLACK RIGHT-POINTING TRIANGLE
▶
and stop=(pause!) should be
U+23F8 DOUBLE VERTICAL BAR
⏸

**Comment by zamojski** [comment]
> "run" should be something like

Please take a look on issue https://github.com/zamojski/TowerCollector/issues/5 . I consider current icon as the right one.

> stop=(pause!) should be

When you press stop it stops, there's no middle state like pause. This feature https://github.com/zamojski/TowerCollector/issues/6 could be considered a pause.

**Comment by jidanni** [comment]
Well OK, but... see also:
https://ux.stackexchange.com/questions/41434/why-is-the-record-icon-always-round-and-usually-red
