### ISSUE TITLE
Not pressing Keep makes one fear one will lose something

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#66]
Here one thinks that the only way to keep this is to press Keep. However of course that is not true. So somehow the buttons should be reworded.

**Comment by jidanni** [comment]
![Screenshot_20191101-100430](https://user-images.githubusercontent.com/1230959/67997658-0328b380-fc90-11e9-9b0a-76b303d1fc28.jpg)

**Comment by zamojski** [comment]
Closed in version 2.2.0.
