### ISSUE TITLE
OCID API key error

### ISSUE THREAD

**Issue by ahangarha** [zamojski/TowerCollector#68]
I cannot upload to OCID due to wrong API key. 

![notification](https://i.imgur.com/JvDVkdJ.png)

![error in the app](https://i.imgur.com/bGkgu6X.png)

**Comment by zamojski** [comment]
Did you put your own free registered API key as the message states? If yes then please check carefully if it's the one you received by email because if copied may contain some invisible characters.

**Comment by ahangarha** [comment]
Hi

Actually not. I thought it would work like mozilla. Then it is my fault.

Sorry

در تاریخ دوشنبه ۹ دسامبر ۲۰۱۹،‏ ۲۳:۱۱ Adam Zamojski <
notifications@github.com> نوشت:
