### ISSUE TITLE
Full Hebrew translation

### ISSUE THREAD

**Issue by yarons** [zamojski/TowerCollector#69]
I almost finished translating to Hebrew, apparently there are an additional 30 words I can't see when I select the appropriate filter.

Can you help me find the missing strings?

I may also need your help with verifying the RTL version of the app (purely cosmetic) so that Hebrew will look native.

Thank you!

**Comment by zamojski** [comment]
There's something wrong with this filter on OneSky tool. I had to manually go through all the phrases. Two of them are missing here:
https://zamojski.oneskyapp.com/collaboration/translate/project/project/14947/language-from/1/language/42/#/file/464304/

Please also translate the Google Play description.
https://zamojski.oneskyapp.com/collaboration/translate/project/project/14946/language/42#/

Thank you very much for all the translation effort!

**Comment by zamojski** [comment]
I see you've finished the translation. I will try to verify it in next few days and then I will publish the update.

**Comment by yarons** [comment]
Cool, I just wanted to mention that this missing strings were actually missing, I contacted the OneSky support team to fix it.

I encourage the transfer to Weblate and I'm willing to help if necessary, OneSky is not as advanced as the other translating platforms and there's no direct git integration which forces you to deal with manual committing to git.

**Comment by zamojski** [comment]
I chose OneSky when Tower Collector wasn't an open source project and only this tool allowed me to have a translation project for free. Later, due to limited time I have, I didn't change it but I will take i t into consideration.
