### ISSUE TITLE
RTL Adjustments

### ISSUE THREAD

**Issue by yarons** [zamojski/TowerCollector#70]
I tested the Hebrew localized version and came to the found the following glitches:

The lables should appear to the right while the data to the left (semicolons are the separators in this case so RTL should be forced on LTR/English text):
![WhatsApp Image 2020-02-07 at 09 10 15(1)](https://user-images.githubusercontent.com/406826/74009124-3794c580-498b-11ea-86fd-2998cd07b1e9.jpeg)

Statistics and saved should switch places, same comment about the labels and data like the former screenshot:
![WhatsApp Image 2020-02-07 at 09 10 15](https://user-images.githubusercontent.com/406826/74009128-395e8900-498b-11ea-842c-7d15e7e5a3ad.jpeg)

The options labels and headers and the upper header should all be right aligned:
![WhatsApp Image 2020-02-07 at 09 10 14(1)](https://user-images.githubusercontent.com/406826/74009133-3bc0e300-498b-11ea-93b2-73b118bc46e9.jpeg)

One of the paragraphs starts with an English character (The name of the product which should not be localized if I understand correctly), one way to deal with it is to add an RLM character before the word Tower, the other way is to force RTL on the entire dialog:
![WhatsApp Image 2020-02-07 at 09 10 14](https://user-images.githubusercontent.com/406826/74009137-3ebbd380-498b-11ea-9b39-6490a8b2ebed.jpeg)

You can make all these changes in layout-he(or iw) so it will be applied to this language only although you'll probably need to do the same for Arabic, Farsi and Urdu anyway.

Thank you!

**Comment by zamojski** [comment]
Linked with #69

**Comment by yarons** [comment]
Indeed, although it's a foundation for the other RTL languages I mentioned.

**Comment by zamojski** [comment]
Closed in version 2.2.0.
