### ISSUE TITLE
Add share option to bottom of export completion page

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#73]
In the menu, tap export. After export is finished it tells you where the directory where the file it exported is. However if we want to go to that place we have to go on our own, so please add a link to that to that place, that we can go in a  browser etc.. And much more importantly after we're finished exporting a file certainly we probably want to share it, perhaps by Gmail. Therefore after export has finished that screen should have a share option at the bottom.

**Comment by zamojski** [comment]
Related to #40.
