### ISSUE TITLE
Gaps due to using other apps?

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#74]
![13475-11](https://user-images.githubusercontent.com/1230959/77830658-00f65280-7165-11ea-9fb3-6aae77fa81f1.jpg)
I noticed on a recent train trip these few kilometer gaps (viewer: viking.)

I never noticed them on walking or city bus trips.

I am thinking perhaps the gaps correspond to times when I took the
cellphone out of my pocket and used some app that used GPS. E.g., map or
city bus apps.

I am thinking other users have never noticed such gaps, because they
have to keep their hands on the steering wheel and thus didn't use any
other apps. (When walking or on a city bus, any gaps wouldn't be so noticeable.)

**Comment by jidanni** [comment]
Let's have a look at one of those gaps,
``
466,92,24000,106157335,148,47,-93,,24.33615023,120.62151096,19.3,17.31,50.3,81,"2020-03-14T23:05:03.802Z",LTE,false,"asus ASUS_Z012DA"
466,92,24000,106157335,148,47,-93,,24.33644727,120.62186741,16.08,17.13,48.5,83,"2020-03-14T23:05:06.802Z",LTE,false,"asus ASUS_Z012DA"
466,92,24000,106157335,148,47,-93,,24.33704150,120.62233865,13.94,16.26,38.3,85,"2020-03-14T23:05:12.800Z",LTE,false,"asus ASUS_Z012DA"
466,92,24000,106157335,148,47,-93,,24.33773288,120.62284583,13.94,15.88,34.6,84,"2020-03-14T23:05:18.787Z",LTE,false,"asus ASUS_Z012DA"
466,92,24000,105465623,144,27,-113,,24.33807468,120.62305635,18.22,14.85,32.1,85,"2020-03-14T23:05:22.810Z",LTE,false,"asus ASUS_Z012DA"
466,92,24500,106694177,453,40,-100,,24.37727105,120.65386144,38.59,8.97,36.2,90,"2020-03-14T23:12:02.825Z",LTE,false,"asus ASUS_Z012DA"
466,92,24000,106157592,31,46,-94,,24.37751869,120.65404579,24.66,8.07,31.1,90,"2020-03-14T23:12:15.970Z",LTE,false,"asus ASUS_Z012DA"
466,92,24500,105981451,206,35,-105,,24.42751166,120.65125177,24.66,28.2,344.9,80,"2020-03-14T23:16:57.811Z",LTE,false,"asus ASUS_Z012DA"
466,92,24500,105981451,206,35,-105,,24.42822388,120.65103693,13.94,27.61,344.8,82,"2020-03-14T23:17:00.805Z",LTE,false,"asus ASUS_Z012DA"
466,92,24500,105981451,206,35,-105,,24.42869558,120.65089652,10.72,27.22,344.9,82,"2020-03-14T23:17:02.800Z",LTE,false,"asus ASUS_Z012DA"
466,92,24500,105981451,206,35,-105,,24.42942348,120.65068000,8.58,27.64,344.6,82,"2020-03-14T23:17:05.714Z",LTE,false,"asus ASUS_Z012DA"

```

**Comment by jidanni** [comment]
It's just like the train went into a tunnel. But it didn't.
Android 8.0, ASUS ZenFone 3.

**Comment by zamojski** [comment]
After analyzing the data I can only say that GPS accuracy was very low - between 13.94 and 38.59 meters (40 meters is the lowest value accepted by Tower Collector).

To be hones I don't see possibility of any influence from other apps as GPS is managed by the system, unless the phone is saving power on apps running in background but this varies by phone manufacturer, Android version and many other things. That makes investigation of such cases out of device almost impossible.
