### ISSUE TITLE
Distinguish CSV versions on save page by giving a hint of their content

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#75]
After the words "CSV" put "(lat,lon,...)"
![Screenshot_20200530-165511](https://user-images.githubusercontent.com/1230959/83324253-906bcf00-a296-11ea-9e44-94a24cf942e4.jpg)
and on the other CSV, put the first two entries also.

The idea is we would then be able to know what we're clicking on.

**Comment by jidanni** [comment]
No, in the field we can't tell which one we are going to get.

**Comment by jidanni** [comment]
No, I haven't checked recently exactly which one is which.

**Comment by jidanni** [comment]
Since the name of open cell ID excetera is not inside the CSV file, the only way for us to tell which one is which when looking at them is if you mention what the first couple column names are,  right there on the save page. That way we can distinguish them without needing to look it up on the internet.

**Comment by zamojski** [comment]
The CSV in OpenCellID format has the _ocid suffix before file extension.
