### ISSUE TITLE
MCC & MNC of CDMA networks aren't correctly reported

### ISSUE THREAD

**Issue by ReimuNotMoe** [zamojski/TowerCollector#79]
Hello. I'm collecting data from a CDMA network. However the MCC & MNC fields of exported CSV files are simply empty.

The app works fine on GSM/LTE networks.

I'm using latest TowerCollector from FDroid.

**Comment by zamojski** [comment]
Thank you for reporting the issue, I personally never had an opportunity to work with CDMA cells because they're not available in my region. The MCC field will be empty but the MNC should contain the value, see the mapping below.
```
mcc = (empty)
mnc = systemId
lac = networkId
cid = baseStationId
```

Can you post some values from your file?

**Comment by zamojski** [comment]
@ReimuNotMoe can you help me by providing sample data?

**Comment by ReimuNotMoe** [comment]
Sorry, I was busy these days.

Here are some data exported from TowerCollector. The MCC & MNC fields are empty.

Since GitHub is a public place, I have to remove some sensitive information.

![image](https://user-images.githubusercontent.com/34613827/91652812-2ea54600-eacd-11ea-8fc1-44937090f4e1.png)


While other apps can see this info correctly.
![image](https://user-images.githubusercontent.com/34613827/91652782-f998f380-eacc-11ea-8edf-4835aa58c9ef.png)

**Comment by zamojski** [comment]
First of all thanks for the screenshots and details! In case of your CSV file the mapping I posted doesn't apply.

I read on Wikipedia under [Mobile country code](https://en.wikipedia.org/wiki/Mobile_country_code) that:

>  Some but not all CDMA, iDEN, and satellite mobile networks are identified with an MCC/MNC tuple as well.

If you take a look on [older](https://developer.android.com/reference/android/telephony/cdma/CdmaCellLocation) and [newer](https://developer.android.com/reference/android/telephony/CellIdentityCdma) Android APIs you'll notice they don't provide MCC nor MNC for CDMA networks. That's the major reason I never considered these 2 properties valid for CDMA.

On the other hand it's technically possible to get the MCC and MNC for CDMA networks using [TelephonyManager.getNetworkOperator()](https://developer.android.com/reference/android/telephony/TelephonyManager#getNetworkOperator()) method but:

> Result may be unreliable on CDMA networks.

The above method of reading network operator becomes more complex in case of multi-SIM phones which are quite popular these days (the method will return the value for the default SIM card). Moreover there's no guarantee this method will work on all cell phones in the same way (I've seem really crazy things taking place around TelephonyManager).

One more comment regarding contribution. The MLS doesn't support CDMA networks at all, the OCID doesn't accept MCC and MNC for the CDMA networks. In that case the value would just appear in the exported files.

To conclude, with your support I may try to read the values but there's no guarantee it will be always working and returning correct values. Will you find some time to test it?

**Comment by zamojski** [comment]
@ReimuNotMoe Will you find some time to test the changes if I make them?

**Comment by zamojski** [comment]
@ReimuNotMoe Any comments from your side? If not then I will close the issue.

**Comment by zamojski** [comment]
Closing as no response and unable to provide tested implementation.
