### ISSUE TITLE
Blue Line barely visible next to Blue Block

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#80]
![Screenshot_20200811-175706_copy_1080x589_copy_270x147.jpg](https://user-images.githubusercontent.com/1230959/89888415-7dfd0280-dc02-11ea-8191-cd1988170235.jpg)

 Here you should perhaps use a different method of distinguishing which block  last saved, vs. statistics, is current instead of the blue line that's right next to the Blue Block because it's barely visible.

**Comment by zamojski** [comment]
The line has default Android height but I will check what I can do with it.

**Comment by jidanni** [comment]
Better would be make the whole white background behind "LAST SAVED" or "STATISTICS" become gold colored upon selection or something.

**Comment by zamojski** [comment]
I will increase the highlight height from 2dp to 5dp. It should be much better visible without being too aggressive or trashy.
