### ISSUE TITLE
Feature Request: Mozilla Stumbler-esque Map View

### ISSUE THREAD

**Issue by Saijin-Naib** [zamojski/TowerCollector#82]
I think it would be really neat to have the option to have a map view similar to Mozilla Stumbler so you can see what towers and other datapoints you're collecting, and what has been collected around you.

**Comment by zamojski** [comment]
Hello Saijin, I want to have the map as well for a few years already. This is one of the features I'm working on right now and should become available in the app in the coming months. Related to #21.
