### ISSUE TITLE
No app can accept the share action

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#85]
Push export. After export push share. It says no app can accept this action.

But that is impossible because I have uk.co.ashtonbrsc.android.intentintercept
Installed, which can accept any action.

**Comment by zamojski** [comment]
Are you sure you've selected Share button? The message is displayed only when Open option is selected.

**Comment by jidanni** [comment]
okay, we have just exported oh, and now the screen looks like this:![Screenshot_20201016-123131.jpg](https://user-images.githubusercontent.com/1230959/96213541-d60e0780-0fab-11eb-8ed4-b3dbbab4e07f.jpg)

**Comment by jidanni** [comment]
Now we tap the share radio button.
![Screenshot_20201016-123145.jpg](https://user-images.githubusercontent.com/1230959/96213571-ec1bc800-0fab-11eb-8633-1d266addce56.jpg)

**Comment by jidanni** [comment]
Okay now we tap the 2nd share that is at the bottom of the screen at the right. And then this is what we see:
![Screenshot_20201016-123131.jpg](https://user-images.githubusercontent.com/1230959/96213678-2b4a1900-0fac-11eb-84cd-bb3e0b7ca600.jpg)

**Comment by jidanni** [comment]
Also one thinks, why am I first pressing a share radio button and then pressing a share button at the bottom of the screen? Something's weird.

**Comment by zamojski** [comment]
This has never happened to me during testing. Which file formats have you selected?

**Comment by jidanni** [comment]
Just the format that makes 2020-10-17-16-11-37.csv.zip .

**Comment by jidanni** [comment]
Same thing happened with uncompressed GPX You know I don't see the logic of having a press the share radio button and then the share word underneath it. There really should be only one press needed to do a share.

Anyway have you ever successfully shared something to Gmail?
