### ISSUE TITLE
Automatically switch to the to the statistics window during uploading

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#89]
Perhaps during uploading, automatically switch to the statistics window.
And maybe have the numbers that are changing highlighted in red or something so people notice them even better.

**Comment by zamojski** [comment]
Closing due to no plans to implement the change. I've the long term plan to implement universal solution combining both export dialog (for upload) and upload notification (for export) visualization and switching to the statistics tab doesn't make sense in that case.
