### ISSUE TITLE
Time of last cell collected perhaps is a smarter export filename stem

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#90]
Perhaps use the time of last cell collected for the export filename
stem. That way the same contents wouldn't have different filename
stems…
```
2020-10-17-16-11-37.csv.zip
2020-10-17-16-11-42.json.zip
2020-10-17-16-11-49.gpx.zip
```
…depending on how fast the person's fingers were, when exporting more
than one version.

Or, I'm exporting last weeks trip when I finally get home. When I look
in the directory I would expect it to be filed under the trip date
(significant) instead of some other date.

**Comment by zamojski** [comment]
The app will use the same filename (except extension) when you select multiple export types instead of running export several times. The change you propose will lead to file name conflicts and may overwrite the files one might have currently changed / opened (locked).

**Comment by jidanni** [comment]
You're right! Upon closer inspection I see those are multiple choice
checkboxes, not single choice radio buttons.
