### ISSUE TITLE
Record EARFCN in export CSV etc.

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#91]
Here (via the [netmonitor app](https://play.google.com/store/apps/details?id=com.parizene.netmonitor)) we see the EARFCN is vital for distinguishing two different signals.

![f](https://user-images.githubusercontent.com/1230959/97638494-9a794000-1a77-11eb-9705-8601db8af3a7.jpg)

Therefore at least it should be part of _exported_ data, for our own studies, even if Mozilla etc. don't use it.

(On the other hand, changes to only the EARFCN don't mean we have changed the cell we are connected to, so might be considered just adding needless lines to our export, if our goal is to simply track cells, not their finer details.)

**Comment by zamojski** [comment]
EARFCN doesn't define the signal strength (here RSRQ does it) but the channel number (frequency). On Android EARFCN is available only for LTE and 5G (NR) cell types.

**Comment by jidanni** [comment]
Oops I meant to say frequency instead of signal.
Anyway as you can see it is a prominent feature of newer apps like
https://play.google.com/store/apps/details?id=make.more.r2d2.google.cellular_pro
and yes, in many countries soon LTE and 5G will be the only systems in the airwaves.

**Comment by jidanni** [comment]
I'm now doing various analyses of my valley, and glad that I have lots of CSVs with data that I didn't think was important at the time, but now am glad that got recorded.

**Comment by jidanni** [comment]
We also see EARFCN (cut off at the bottom of the second picture) on https://play.google.com/store/apps/details?id=net.sf.rhino.rxmonitor .

**Comment by zamojski** [comment]
Related to #36

**Comment by jidanni** [comment]
(Ah, GitHub made me look bad, in public, again!

I swore I already submitted this issue, but
https://github.com/zamojski/TowerCollector/search?q=EARFCN
didn't find it (A).

Or, actually it did, but really tiny, (B).
![13547-0](https://user-images.githubusercontent.com/1230959/97776059-4ddd5400-1ba0-11eb-9514-563afcbb8bd5.jpg)

Yes, it does indeed say "...find any **code** matching..." but hey, I launched the search from the **issues** page:

![1460-1](https://user-images.githubusercontent.com/1230959/97776187-ff7c8500-1ba0-11eb-9b97-ab70d528927f.jpg)



OK, I'll tell GitHub, again.)
