### ISSUE TITLE
Français Translation

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [zamojski/TowerCollector#95]
[French Translation](https://zamojski.oneskyapp.com/collaboration/translate/project/project/14947/language/5#/ is finished)

**Comment by zamojski** [comment]
@mondlicht-und-sterne Thank you for letting me know!

There're just a few phrases that are out of date, see:
https://zamojski.oneskyapp.com/collaboration/translate/project/project/14947/language/5#/filter/outdated/
