### ISSUE TITLE
OCID API Key format out of date

### ISSUE THREAD

**Issue by kousu** [zamojski/TowerCollector#96]
TowerCollector suggests that to make uploads to opencellid.org work I should find an API key in one of these three formats:

![tc](https://user-images.githubusercontent.com/987487/101237792-842f5700-36a9-11eb-9f22-c933e5e8fe5c.jpeg)

But trying to get one after making an account on https://opencellid.org is confusing because

1. They no longer call it an API key, it's a "Access Token"
2. The format is now `pk\.[[:digit:]]{32}`

![2020-12-05-031942_1362x729_scrot](https://user-images.githubusercontent.com/987487/101237833-e1c3a380-36a9-11eb-8648-84f9b7b56b89.png)
![2020-12-05-031951_1362x729_scrot](https://user-images.githubusercontent.com/987487/101237834-e1c3a380-36a9-11eb-9462-c25c612553e3.png)

I found that just removing the "pk." from my Access Token and entering that was enough to make uploads function.

Version: 2.6.0 from the F-Droid repo

**Comment by zamojski** [comment]
I didn't know about the new format. I will update the app but for the time being you can ignore the the warning in the app because it will try to upload the measurements anyway.

**Comment by kousu** [comment]
Thanks!

I just noticed that you do mention their nomenclature: "API Key (token)" . But for first-time users it'd be helpful if that was reversed: "Access Token (API key)" or just "Access token".

**Comment by zamojski** [comment]
@TheWood7 On the https://opencellid.org/ page there's a search but you need to provide all 4 parameters z, Cell ID is not sufficient.
