### ISSUE TITLE
Red man on the map

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#97]
The user sees a button with a red hiker man on the map but does not know what it means. The problem is there is no way for him to find out what it means.
It's true there is also a button with a dot in the middle of it. But the user might already know what that means so nevermind.

**Comment by zamojski** [comment]
There's a description of the button, just long press it ans you'll see.
![obraz](https://user-images.githubusercontent.com/12007817/103374187-33a7ef80-4ad7-11eb-9d82-b3b88194dfc6.png)

**Comment by jidanni** [comment]
That is the only place I didn't try. Okay. I guess I'll have to get used to doing that. (Usually one doesn't just go pushing on buttons to see what they do ... like the president's nuke button.)

**Comment by zamojski** [comment]
It's a typical feature of Android to long press a button to see it's meaning. It works in the similar way for the buttons on the toolbar.
