### ISSUE TITLE
OpenStreetMap Attribution

### ISSUE THREAD

**Issue by jt15s** [zamojski/TowerCollector#98]
Hey there, 

I am a mapper for OpenStreetMap (OSM) and noticed the Tower Collector app uses OSM but without attribution. OSM is licensed under the Open Database License which states that you must provide attribution. 

A lot of software developers simply ignore requests for attribution, even though not following the license is _technically_ against the law. Hence, we would appreciate if you implemented attribution as soon as you can. 

[You can find more information as well as examples of correct attribution here.](https://www.openstreetmap.org/copyright)

Thanks!

Kind Regards, 

jt15s (on behalf of the OSM community of mappers)

**Comment by zamojski** [comment]
Hi @jt15s, I missed that part when integrating the map component. I will do it by the end of the week. Thanks for raising the issue promptly!

**Comment by jt15s** [comment]
> Hi @jt15s, I missed that part when integrating the map component. I will do it by the end of the week. Thanks for raising the issue promptly!

No worries! Thanks so much for your prompt reply!

**Comment by zamojski** [comment]
Would it be ok like this? It looks like the standard CopyrightOverlay in osmdroid doesn't support links.
![obraz](https://user-images.githubusercontent.com/12007817/103430405-038a4a80-4bc4-11eb-806a-19b0d14adee1.png)

**Comment by jt15s** [comment]
> Would it be ok like this? It looks like the standard CopyrightOverlay in osmdroid doesn't support links.
> ![obraz](https://user-images.githubusercontent.com/12007817/103430405-038a4a80-4bc4-11eb-806a-19b0d14adee1.png)

I don't think so, unfortunately, the Copyright notice says that you must link to the Copyright page. However, it also says that:
>In media where links are not possible (e.g. printed works), we suggest you direct your readers to openstreetmap.org (perhaps by expanding 'OpenStreetMap' to this full address) and to opendatacommons.org.

You could do that, but a link is the preferred option. Maybe see if there is another overlay you could use? 

One more thing too, the attribution is usually placed on the bottom right-hand corner of the map. If you could change it that would be great!

Thanks and Happy New Year!

**Comment by zamojski** [comment]
I've added a label with the link over the map instead of the CopyrightOverlay. It seems to looks fine and the links works.

![obraz](https://user-images.githubusercontent.com/12007817/103435662-fe53ec80-4c11-11eb-90d6-1bc37cafe0b5.png)

**Comment by jt15s** [comment]
> I've added a label with the link over the map instead of the CopyrightOverlay. It seems to looks fine and the links works.
> 
> ![obraz](https://user-images.githubusercontent.com/12007817/103435662-fe53ec80-4c11-11eb-90d6-1bc37cafe0b5.png)

That'll do perfectly! Thanks again!
